"use client";/* eslint-disable @typescript-eslint/no-explicit-any */
import {FormEvent,useEffect,useState} from "react";
import {api,json} from "@/app/lib/api";
import {EmptyState,Icons,Notice,PageHeader} from "./DesignSystem";
const labels:Record<string,string>={FORM_VIEW:"Visualizar formulários",FORM_CREATE:"Criar formulários",FORM_EDIT:"Editar formulários",FORM_PUBLISH:"Publicar formulários",FORM_ARCHIVE:"Arquivar formulários",FORM_USE:"Utilizar no aplicativo",FORM_MANAGE_ACCESS:"Gerenciar acesso a formulários",USER_VIEW:"Visualizar equipe",USER_CREATE:"Adicionar pessoas",USER_UPDATE:"Atualizar pessoas",USER_SUSPEND:"Suspender pessoas",SUBMISSION_VIEW:"Visualizar respostas",SUBMISSION_EXPORT:"Exportar respostas",TENANT_MANAGE:"Administrar empresa"};
export default function AccessPanel({tenantId}:{tenantId:string}){
 const [roles,setRoles]=useState<any[]>([]),[catalog,setCatalog]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[forms,setForms]=useState<any[]>([]),[access,setAccess]=useState<any>({assignments:[],grants:[]}),[tab,setTab]=useState("roles"),[selectedRole,setSelectedRole]=useState(""),[message,setMessage]=useState("");
 const load=()=>Promise.all([api<any[]>(`tenants/${tenantId}/permissions/roles`),api<any[]>(`tenants/${tenantId}/permissions/catalog`),api<any[]>(`tenants/${tenantId}/users`),api<any[]>(`tenants/${tenantId}/forms`),api<any>(`tenants/${tenantId}/permissions/access`)]).then(([r,c,u,f,a])=>{setRoles(r);setCatalog(c);setUsers(u);setForms(f);setAccess(a);setSelectedRole(x=>x||r[0]?.id||"")});useEffect(load,[tenantId]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();await api(`tenants/${tenantId}/permissions/roles`,json("POST",Object.fromEntries(new FormData(e.currentTarget))));e.currentTarget.reset();setMessage("Papel criado com sucesso.");load()}
 async function permission(role:any,code:string,on:boolean){await api(`tenants/${tenantId}/permissions/roles/${role.id}/permissions`,json("PUT",{permissions:on?[...role.permissions,code]:role.permissions.filter((x:string)=>x!==code)}));setMessage("Permissões atualizadas.");load()}
 async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api(`tenants/${tenantId}/permissions/roles/${d.roleId}/members/${d.membershipId}`,{method:"POST"});setMessage("Papel atribuído.");load()}
 async function grant(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const principal=d.principalType==="member"?{membershipId:d.principalId}:{roleId:d.principalId};await api(`tenants/${tenantId}/permissions/forms/${d.formId}/grants`,json("POST",{...principal,permission:d.permission}));setMessage("Acesso específico concedido.");load()}
 async function unassign(a:any){await api(`tenants/${tenantId}/permissions/roles/${a.roleId}/members/${a.membershipId}`,{method:"DELETE"});load()}async function revoke(id:string){await api(`tenants/${tenantId}/permissions/grants/${id}`,{method:"DELETE"});load()}
 const person=(id:string)=>users.find(u=>u.membershipId===id)?.displayName??"Pessoa";const roleName=(id:string)=>roles.find(r=>r.id===id)?.name??"Papel";const current=roles.find(r=>r.id===selectedRole);
 return <div className="page"><PageHeader eyebrow="Segurança" title="Papéis e acessos" description="Configure permissões por responsabilidade e exceções específicas por formulário."/>{message&&<Notice tone="success">{message}</Notice>}<div className="access-tabs" role="tablist"><button className={tab==="roles"?"active":""} onClick={()=>setTab("roles")}><Icons.shield/>Papéis e permissões</button><button className={tab==="members"?"active":""} onClick={()=>setTab("members")}><Icons.people/>Atribuições</button><button className={tab==="forms"?"active":""} onClick={()=>setTab("forms")}><Icons.forms/>Acesso por formulário</button></div>
 {tab==="roles"&&<div className="access-layout"><aside className="panel role-list"><div><h2>Papéis</h2><p className="muted">Selecione para configurar.</p></div>{roles.map(r=><button key={r.id} className={selectedRole===r.id?"active":""} onClick={()=>setSelectedRole(r.id)}><span><strong>{r.name}</strong><small>{r.permissions.length} permissões</small></span><Icons.arrowRight/></button>)}<form onSubmit={create}><h3>Novo papel</h3><label>Nome<input name="name" required/></label><label>Descrição<input name="description"/></label><button className="primary"><Icons.add/>Criar papel</button></form></aside><section className="panel role-permissions">{current?<><div><span className="eyebrow">Permissões efetivas</span><h2>{current.name}</h2><p className="muted">{current.description||"Sem descrição"}</p></div><div className="permission-grid">{catalog.map(p=><label key={p.code}><input type="checkbox" checked={current.permissions.includes(p.code)} onChange={e=>permission(current,p.code,e.target.checked)}/><span><strong>{labels[p.code]??p.code}</strong><small>{p.description}</small></span></label>)}</div></>:<EmptyState icon={Icons.shield} title="Nenhum papel criado" description="Crie um papel para agrupar permissões."/>}</section></div>}
 {tab==="members"&&<div className="split"><form className="panel" onSubmit={assign}><h2>Atribuir papel</h2><p className="muted">Uma pessoa pode receber mais de um papel.</p><label>Pessoa<select name="membershipId">{users.filter(u=>u.membershipType==="MEMBER").map(u=><option key={u.membershipId} value={u.membershipId}>{u.displayName}</option>)}</select></label><label>Papel<select name="roleId">{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="primary">Atribuir papel</button></form><section className="panel"><h2>Atribuições ativas</h2>{access.assignments.map((a:any)=><div className="access-row" key={`${a.membershipId}-${a.roleId}`}><span><strong>{person(a.membershipId)}</strong><small>{roleName(a.roleId)}</small></span><button className="danger" onClick={()=>unassign(a)}>Remover</button></div>)}{!access.assignments.length&&<EmptyState icon={Icons.people} title="Nenhuma atribuição" description="As relações entre pessoas e papéis aparecerão aqui."/>}</section></div>}
 {tab==="forms"&&<div className="split"><form className="panel" onSubmit={grant}><h2>Conceder acesso específico</h2><p className="muted">Use exceções apenas quando um papel geral não for suficiente.</p><label>Formulário<select name="formId">{forms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Destino<select name="principalType"><option value="member">Pessoa</option><option value="role">Papel</option></select></label><label>Pessoa ou papel<select name="principalId">{users.filter(u=>u.membershipType==="MEMBER").map(u=><option key={u.membershipId} value={u.membershipId}>{u.displayName}</option>)}{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Permissão<select name="permission"><option value="FORM_VIEW">Visualizar formulário</option><option value="FORM_USE">Utilizar formulário</option><option value="FORM_EDIT">Editar formulário</option><option value="SUBMISSION_VIEW">Visualizar respostas</option></select></label><button className="primary">Conceder acesso</button></form><section className="panel"><h2>Concessões específicas</h2>{access.grants.map((g:any)=><div className="access-row" key={g.id}><span><strong>{forms.find(f=>f.id===g.formId)?.name??"Formulário"}</strong><small>{labels[g.permission]??g.permission} · {g.membershipId?person(g.membershipId):roleName(g.roleId)}</small></span><button className="danger" onClick={()=>revoke(g.id)}>Revogar</button></div>)}{!access.grants.length&&<EmptyState icon={Icons.forms} title="Nenhuma exceção" description="O acesso está sendo definido somente pelos papéis gerais."/>}</section></div>}</div>
}
