"use client";/* eslint-disable @typescript-eslint/no-explicit-any */
import {FormEvent,useEffect,useState} from "react";import {api,json} from "@/app/lib/api";
export default function AccessPanel({tenantId}:{tenantId:string}){
 const [roles,setRoles]=useState<any[]>([]),[catalog,setCatalog]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[forms,setForms]=useState<any[]>([]),[access,setAccess]=useState<any>({assignments:[],grants:[]});
 const load=()=>Promise.all([api<any[]>(`tenants/${tenantId}/permissions/roles`),api<any[]>(`tenants/${tenantId}/permissions/catalog`),api<any[]>(`tenants/${tenantId}/users`),api<any[]>(`tenants/${tenantId}/forms`),api<any>(`tenants/${tenantId}/permissions/access`)]).then(([r,c,u,f,a])=>{setRoles(r);setCatalog(c);setUsers(u);setForms(f);setAccess(a)});useEffect(load,[tenantId]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();await api(`tenants/${tenantId}/permissions/roles`,json('POST',Object.fromEntries(new FormData(e.currentTarget))));e.currentTarget.reset();load()}
 async function permission(role:any,code:string,on:boolean){await api(`tenants/${tenantId}/permissions/roles/${role.id}/permissions`,json('PUT',{permissions:on?[...role.permissions,code]:role.permissions.filter((x:string)=>x!==code)}));load()}
 async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api(`tenants/${tenantId}/permissions/roles/${d.roleId}/members/${d.membershipId}`,{method:'POST'});load()}
 async function grant(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const principal=d.principalType==='member'?{membershipId:d.principalId}:{roleId:d.principalId};await api(`tenants/${tenantId}/permissions/forms/${d.formId}/grants`,json('POST',{...principal,permission:d.permission}));load()}
 async function unassign(a:any){await api(`tenants/${tenantId}/permissions/roles/${a.roleId}/members/${a.membershipId}`,{method:'DELETE'});load()}
 async function revoke(id:string){await api(`tenants/${tenantId}/permissions/grants/${id}`,{method:'DELETE'});load()}
 const name=(a:any)=>users.find(u=>u.membershipId===a.membershipId)?.displayName??'Pessoa';const role=(id:string)=>roles.find(r=>r.id===id)?.name??'Papel';
 return <div className="page"><header className="page-head"><div><span className="kicker">SEGURANÇA</span><h1>Papéis e acessos</h1><p>Defina permissões gerais e liberações específicas por formulário.</p></div></header><div className="split"><form className="panel" onSubmit={create}><h2>Novo papel</h2><label>Nome<input name="name" required/></label><label>Descrição<input name="description"/></label><button className="primary">Criar papel</button></form><form className="panel" onSubmit={assign}><h2>Atribuir papel</h2><label>Pessoa<select name="membershipId">{users.filter(u=>u.membershipType==='MEMBER').map(u=><option key={u.membershipId} value={u.membershipId}>{u.displayName}</option>)}</select></label><label>Papel<select name="roleId">{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="primary">Atribuir</button></form></div>{roles.map(r=><article className="role-card" key={r.id}><h3>{r.name}</h3><p>{r.description}</p><div className="permission-grid">{catalog.map(p=><label key={p.code}><input type="checkbox" checked={r.permissions.includes(p.code)} onChange={e=>permission(r,p.code,e.target.checked)}/><span><strong>{p.code}</strong><small>{p.description}</small></span></label>)}</div></article>)}<div className="split access-lists"><section className="panel"><h2>Atribuições ativas</h2>{access.assignments.map((a:any)=><div className="access-row" key={`${a.membershipId}-${a.roleId}`}><span><strong>{name(a)}</strong><small>{role(a.roleId)}</small></span><button onClick={()=>unassign(a)}>Remover</button></div>)}{!access.assignments.length&&<p className="muted">Nenhum papel atribuído.</p>}</section><form className="panel" onSubmit={grant}><h2>Acesso por formulário</h2><label>Formulário<select name="formId">{forms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Destino<select name="principalType"><option value="member">Pessoa</option><option value="role">Papel</option></select></label><label>Pessoa ou papel<select name="principalId">{users.filter(u=>u.membershipType==='MEMBER').map(u=><option key={u.membershipId} value={u.membershipId}>{u.displayName}</option>)}{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Permissão<select name="permission"><option>FORM_VIEW</option><option>FORM_USE</option><option>FORM_EDIT</option><option>SUBMISSION_VIEW</option></select></label><button className="primary">Conceder acesso</button></form></div><section className="panel grants"><h2>Concessões específicas</h2>{access.grants.map((g:any)=><div className="access-row" key={g.id}><span><strong>{forms.find(f=>f.id===g.formId)?.name??'Formulário'}</strong><small>{g.permission} · {g.membershipId?name(g):role(g.roleId)}</small></span><button onClick={()=>revoke(g.id)}>Revogar</button></div>)}{!access.grants.length&&<p className="muted">Nenhuma concessão específica.</p>}</section></div>
}
