/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import Link from "next/link";import {FormEvent,useState} from "react";
export default function AuthForm({mode}:{mode:"login"|"register"}){
 const [error,setError]=useState("");const [busy,setBusy]=useState(false);const register=mode==="register";
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget));
  const payload=register?{tenantName:data.tenantName,tenantSlug:data.tenantSlug,displayName:data.displayName,email:data.email,password:data.password,deviceName:"InspecTeam Web"}:{email:data.email,password:data.password,deviceName:"InspecTeam Web"};
  const response=await fetch(`/gateway/auth/${register?"register":"login"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});
  if(!response.ok){let p:any={};try{p=await response.json()}catch{}setError(p.detail??"Confira os dados e tente novamente.");setBusy(false);return;}
  const p=await response.json();if(p.tenantId)localStorage.setItem("inspecteam_tenant",p.tenantId);const params=new URLSearchParams(location.search);location.href=params.get("returnTo")||"/app";
 }
 return <main className="auth-page"><section className="auth-brand"><div className="brand-lockup"><span className="brand-mark">I</span>InspecTeam</div><div><span className="kicker">OPERAÇÃO SEM PAPEL</span><h1>Inspeções confiáveis, mesmo longe da internet.</h1><p>Crie checklists, organize sua equipe e acompanhe cada execução em um só lugar.</p></div><div className="auth-proof"><strong>Projetado para o campo</strong><span>Formulários versionados · Permissões granulares · Offline-first</span></div></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div><span className="kicker">{register?"COMECE AGORA":"BEM-VINDO DE VOLTA"}</span><h2>{register?"Crie sua operação":"Acesse sua conta"}</h2><p>{register?"Configure sua empresa e publique o primeiro formulário.":"Entre para continuar gerenciando sua equipe."}</p></div>{register&&<><label>Nome da empresa<input name="tenantName" required maxLength={160}/></label><label>Identificador da empresa<input name="tenantSlug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="guincho-central"/></label><label>Seu nome<input name="displayName" required maxLength={160}/></label></>}<label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha<input name="password" type="password" minLength={register?10:1} autoComplete={register?"new-password":"current-password"} required/></label>{error&&<div className="alert error" role="alert">{error}</div>}<button className="primary wide" disabled={busy}>{busy?"Aguarde...":register?"Criar empresa":"Entrar"}</button><p className="auth-switch">{register?"Já tem uma conta?":"Ainda não tem uma conta?"} <Link href={register?"/login":"/cadastro"}>{register?"Entrar":"Criar empresa"}</Link></p></form></section></main>
}
