"use client";
import type { ReactNode } from "react";
import {Add20Regular,Archive20Regular,ArrowDown20Regular,ArrowRight20Regular,ArrowUp20Regular,Building24Regular,CheckmarkCircle20Filled,ChevronDown20Regular,ClipboardTaskListLtr24Regular,Copy20Regular,Delete20Regular,Dismiss20Regular,DocumentBulletList24Regular,Edit20Regular,Eye20Regular,Home24Regular,Key20Regular,LockClosed20Regular,MoreHorizontal20Regular,Navigation24Regular,PeopleTeam24Regular,PersonAccounts24Regular,PersonAdd20Regular,Save20Regular,Search20Regular,Send20Regular,Settings24Regular,ShieldKeyhole24Regular,SignOut24Regular,Warning20Filled,Calendar20Regular,CheckboxChecked20Regular,Clock20Regular,Image20Regular,MultiselectLtr20Regular,NumberSymbol20Regular,RadioButton20Regular,Signature20Regular,TextBulletListSquare20Regular,TextDescription20Regular,TextField20Regular,TextHeader120Regular} from "@fluentui/react-icons";
export const Icons={add:Add20Regular,archive:Archive20Regular,arrowDown:ArrowDown20Regular,arrowRight:ArrowRight20Regular,arrowUp:ArrowUp20Regular,building:Building24Regular,check:CheckmarkCircle20Filled,chevron:ChevronDown20Regular,clipboard:ClipboardTaskListLtr24Regular,copy:Copy20Regular,delete:Delete20Regular,dismiss:Dismiss20Regular,forms:DocumentBulletList24Regular,edit:Edit20Regular,eye:Eye20Regular,home:Home24Regular,key:Key20Regular,lock:LockClosed20Regular,more:MoreHorizontal20Regular,navigation:Navigation24Regular,people:PeopleTeam24Regular,person:PersonAccounts24Regular,personAdd:PersonAdd20Regular,save:Save20Regular,search:Search20Regular,send:Send20Regular,settings:Settings24Regular,shield:ShieldKeyhole24Regular,signOut:SignOut24Regular,warning:Warning20Filled,fieldText:TextField20Regular,fieldLongText:TextDescription20Regular,fieldNumber:NumberSymbol20Regular,fieldDate:Calendar20Regular,fieldTime:Clock20Regular,fieldSelect:RadioButton20Regular,fieldMultiSelect:MultiselectLtr20Regular,fieldCheckbox:CheckboxChecked20Regular,fieldPhoto:Image20Regular,fieldSignature:Signature20Regular,fieldHeading:TextHeader120Regular,fieldInstructions:TextBulletListSquare20Regular};
export function PageHeader({eyebrow,title,description,action,children}:{eyebrow?:string;title:string;description?:string;action?:ReactNode;children?:ReactNode}){return <header className="page-header"><div className="page-header-copy">{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}{children}</div>{action&&<div className="page-actions">{action}</div>}</header>}
export function StatusBadge({status}:{status:string}){const value=status.toLowerCase();const labels:Record<string,string>={active:"Ativo",suspended:"Suspenso",archived:"Arquivado",published:"Publicado",draft:"Rascunho",completed:"Concluído",pending:"Pendente",owner:"Proprietário",member:"Membro",platform_admin:"Suporte da plataforma"};return <span className={`status-badge status-${value}`}>{labels[value]??status}</span>}
export function EmptyState({icon:Icon=Icons.clipboard,title,description,action}:{icon?:typeof Icons.home;title:string;description:string;action?:ReactNode}){return <div className="empty-state"><span className="empty-icon"><Icon/></span><h3>{title}</h3><p>{description}</p>{action}</div>}
export function Notice({tone="info",title,children}:{tone?:"info"|"success"|"warning"|"danger";title?:string;children:ReactNode}){const Icon=tone==="success"?Icons.check:tone==="warning"||tone==="danger"?Icons.warning:Icons.shield;return <div className={`notice notice-${tone}`} role={tone==="danger"?"alert":"status"}><Icon/><div>{title&&<strong>{title}</strong>}<span>{children}</span></div></div>}
export function Dialog({title,description,confirmLabel="Confirmar",tone="primary",busy,onConfirm,onClose}:{title:string;description:string;confirmLabel?:string;tone?:"primary"|"danger";busy?:boolean;onConfirm:()=>void;onClose:()=>void}){return <div className="dialog-backdrop" onMouseDown={onClose}><section className="dialog" role="alertdialog" aria-modal="true" aria-labelledby="dialog-title" aria-describedby="dialog-description" onMouseDown={e=>e.stopPropagation()}><span className={`dialog-symbol ${tone}`}><Icons.warning/></span><div><h2 id="dialog-title">{title}</h2><p id="dialog-description">{description}</p></div><div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button type="button" className={`button ${tone}`} onClick={onConfirm} disabled={busy}>{busy?"Processando...":confirmLabel}</button></div></section></div>}
