"use client";
import Link from "next/link";
import {type PointerEvent,useEffect,useRef,useState} from "react";
import {api,json} from "@/app/lib/api";
import {Icons,Notice,PageHeader} from "./DesignSystem";

type Field={id:string;type:string;label:string;description?:string;required?:boolean;options?:string[]};
type Section={id:string;title:string;description?:string;fields:Field[]};
type PublishedForm={id:string;name:string;description?:string;versionId:string;version:number;definition:{sections:Section[]}};
type UploadSession={fileId:string;objectKey:string;uploadUrl:string;expiresInSeconds:number};
type Answer=string|number|boolean|string[]|{fileId:string;objectKey:string;originalName:string;contentType:string}|null;

export default function FormRunner({tenantId,formId}:{tenantId:string;formId:string}){
 const[form,setForm]=useState<PublishedForm>(),[answers,setAnswers]=useState<Record<string,Answer>>({}),[files,setFiles]=useState<Record<string,File>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[submitted,setSubmitted]=useState(false);
 const submissionId=useRef(crypto.randomUUID());
 useEffect(()=>{api<PublishedForm>(`tenants/${tenantId}/forms/${formId}/published`).then(setForm).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[tenantId,formId]);
 function setAnswer(id:string,value:Answer){setAnswers(current=>({...current,[id]:value}));setErrors(current=>({...current,[id]:""}))}
 function validate(){const next:Record<string,string>={};for(const section of form?.definition.sections??[])for(const field of section.fields){if(!field.required||["heading","instructions"].includes(field.type))continue;const value=["photo","signature"].includes(field.type)?files[field.id]:answers[field.id];const empty=value===undefined||value===null||value===""||Array.isArray(value)&&value.length===0||field.type==="checkbox"&&value!==true;if(empty)next[field.id]="Este campo é obrigatório."}setErrors(next);return Object.keys(next).length===0}
 async function upload(field:Field,file:File){if(file.size>20*1024*1024)throw new Error(`O arquivo de ${field.label} ultrapassa 20 MB.`);const session=await api<UploadSession>(`tenants/${tenantId}/files/upload-sessions`,json("POST",{formId,submissionId:submissionId.current,fieldId:field.id,originalName:file.name,contentType:file.type||"application/octet-stream",sizeBytes:file.size}));const sent=await fetch(session.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type||"application/octet-stream"},body:file});if(!sent.ok)throw new Error(`Não foi possível enviar o arquivo de ${field.label}.`);await api(`tenants/${tenantId}/files/${session.fileId}/complete`,json("POST",{formId}));return{fileId:session.fileId,objectKey:session.objectKey,originalName:file.name,contentType:file.type||"application/octet-stream"}}
 async function submit(){if(!form||!validate())return;setSubmitting(true);setError("");try{const finalAnswers={...answers};await api(`tenants/${tenantId}/submissions`,json("POST",{id:submissionId.current,formId,formVersionId:form.versionId,answers:finalAnswers,clientCreatedAt:new Date().toISOString()}));let revision=0;const attachmentFields=form.definition.sections.flatMap(section=>section.fields).filter(field=>["photo","signature"].includes(field.type)&&files[field.id]);for(const field of attachmentFields)finalAnswers[field.id]=await upload(field,files[field.id]);if(attachmentFields.length){await api(`tenants/${tenantId}/submissions/${submissionId.current}`,json("PATCH",{formId,revision,answers:finalAnswers}));revision++}await api(`tenants/${tenantId}/submissions/${submissionId.current}/complete`,json("POST",{formId,revision,answers:finalAnswers}));setSubmitted(true)}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível enviar a resposta.")}finally{setSubmitting(false)}}
 if(loading)return <div className="center-state" role="status" aria-live="polite"><span className="loader"/><p>Carregando formulário...</p></div>;
 if(!form)return <div className="page"><Notice tone="danger">{error||"Formulário publicado não encontrado."}</Notice><Link className="button secondary" href="/app/formularios">Voltar aos formulários</Link></div>;
 if(submitted)return <div className="page runner-success" role="status" aria-live="polite"><span className="runner-success-icon"><Icons.check/></span><h1>Resposta enviada</h1><p>O formulário <strong>{form.name}</strong> foi concluído e já está disponível no histórico de respostas.</p><div><Link className="button primary" href="/app/formularios">Voltar aos formulários</Link><Link className="button secondary" href="/app/respostas">Ver respostas</Link></div></div>;
 return <div className="page form-runner"><PageHeader eyebrow={`Formulário publicado · v${form.version}`} title={form.name} description={form.description||"Preencha os campos abaixo e envie quando concluir."} action={<Link className="button secondary" href="/app/formularios">Cancelar</Link>}/>{error&&<Notice tone="danger">{error}</Notice>}<form onSubmit={event=>{event.preventDefault();void submit()}}><div className="runner-sections">{form.definition.sections.map((section,index)=><section className="runner-section" key={section.id}><header><span>{String(index+1).padStart(2,"0")}</span><div><h2>{section.title}</h2>{section.description&&<p>{section.description}</p>}</div></header><div className="runner-fields">{section.fields.map(field=><RunnerField key={field.id} field={field} value={answers[field.id]} file={files[field.id]} error={errors[field.id]} onValue={value=>setAnswer(field.id,value)} onFile={file=>{setFiles(current=>file?{...current,[field.id]:file}:Object.fromEntries(Object.entries(current).filter(([id])=>id!==field.id)));setErrors(current=>({...current,[field.id]:""}))}}/>)}</div></section>)}</div><div className="runner-submit" aria-live="polite"><p>Revise suas informações antes de finalizar. Após o envio, a resposta ficará registrada no histórico.</p><button className="primary" disabled={submitting}><Icons.send/>{submitting?"Enviando...":"Enviar resposta"}</button></div></form></div>
}

function RunnerField({field,value,file,error,onValue,onFile}:{field:Field;value?:Answer;file?:File;error?:string;onValue:(value:Answer)=>void;onFile:(file?:File)=>void}){
 if(field.type==="heading")return <div className="runner-heading"><h3>{field.label}</h3>{field.description&&<p>{field.description}</p>}</div>;
 if(field.type==="instructions")return <div className="runner-instructions"><Icons.clipboard/><div><strong>{field.label}</strong>{field.description&&<p>{field.description}</p>}</div></div>;
 const id=`field-${field.id}`,describedBy=error?`${id}-error`:field.description?`${id}-help`:undefined;
 const label=<>{field.label}{field.required&&<span className="required" aria-hidden="true"> *</span>}</>;
 let control;
 if(field.type==="textarea")control=<textarea id={id} value={String(value??"")} onChange={event=>onValue(event.target.value)} aria-invalid={!!error} aria-describedby={describedBy}/>;
 else if(field.type==="select")control=<select id={id} value={String(value??"")} onChange={event=>onValue(event.target.value)} aria-invalid={!!error} aria-describedby={describedBy}><option value="">Selecione</option>{(field.options??[]).map(option=><option key={option}>{option}</option>)}</select>;
 else if(field.type==="multiselect")control=<select id={id} multiple value={Array.isArray(value)?value:[]} onChange={event=>onValue(Array.from(event.target.selectedOptions,option=>option.value))} aria-invalid={!!error} aria-describedby={describedBy}>{(field.options??[]).map(option=><option key={option}>{option}</option>)}</select>;
 else if(field.type==="checkbox")control=<label className="runner-check"><input id={id} type="checkbox" checked={value===true} onChange={event=>onValue(event.target.checked)} aria-invalid={!!error} aria-describedby={describedBy}/><span>{field.description||"Confirmar"}</span></label>;
 else if(field.type==="photo")control=<div className="photo-input"><input id={id} type="file" accept="image/*" capture="environment" onChange={event=>onFile(event.target.files?.[0])} aria-invalid={!!error} aria-describedby={describedBy}/>{file&&<small>Selecionado: {file.name}</small>}</div>;
 else if(field.type==="signature")control=<SignaturePad id={id} file={file} invalid={!!error} describedBy={describedBy} onFile={onFile}/>;
 else control=<input id={id} type={field.type==="number"?"number":field.type==="date"?"date":field.type==="time"?"time":"text"} value={String(value??"")} onChange={event=>onValue(event.target.value)} aria-invalid={!!error} aria-describedby={describedBy}/>;
 return <div className={`runner-field ${error?"has-error":""}`}><label htmlFor={field.type==="checkbox"?undefined:id}>{label}</label>{control}{field.description&&!["checkbox"].includes(field.type)&&<small id={`${id}-help`} className="field-help">{field.description}</small>}{field.type==="signature"&&<small className="field-help">Assine no quadro usando mouse, caneta ou toque.</small>}{error&&<small id={`${id}-error`} className="field-error" role="alert">{error}</small>}</div>
}

function SignaturePad({id,file,invalid,describedBy,onFile}:{id:string;file?:File;invalid:boolean;describedBy?:string;onFile:(file?:File)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),[typed,setTyped]=useState("");
 function point(event:PointerEvent<HTMLCanvasElement>){const element=canvas.current!,rect=element.getBoundingClientRect();return{x:(event.clientX-rect.left)*(element.width/rect.width),y:(event.clientY-rect.top)*(element.height/rect.height)}}
 function start(event:PointerEvent<HTMLCanvasElement>){const element=canvas.current!,context=element.getContext("2d");if(!context)return;event.preventDefault();element.setPointerCapture(event.pointerId);const p=point(event);context.beginPath();context.moveTo(p.x,p.y);context.lineWidth=4;context.lineCap="round";context.lineJoin="round";context.strokeStyle=getComputedStyle(element).getPropertyValue("--text").trim()||"#163843";drawing.current=true}
 function move(event:PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;event.preventDefault();const context=canvas.current?.getContext("2d");if(!context)return;const p=point(event);context.lineTo(p.x,p.y);context.stroke()}
 function finish(event:PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;drawing.current=false;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);canvas.current?.toBlob(blob=>{if(blob)onFile(new File([blob],"assinatura.png",{type:"image/png"}))},"image/png")}
 function signName(){const element=canvas.current,context=element?.getContext("2d");if(!element||!context||!typed.trim())return;context.clearRect(0,0,element.width,element.height);context.fillStyle=getComputedStyle(element).getPropertyValue("--text").trim()||"#163843";context.font="italic 52px sans-serif";context.fillText(typed.trim(),42,140);element.toBlob(blob=>{if(blob)onFile(new File([blob],"assinatura.png",{type:"image/png"}))},"image/png")}
 function clear(){const element=canvas.current,context=element?.getContext("2d");if(element&&context)context.clearRect(0,0,element.width,element.height);setTyped("");onFile(undefined)}
 return <div className="signature-pad"><canvas id={id} ref={canvas} width="900" height="240" tabIndex={0} aria-label="Área para desenhar a assinatura" aria-invalid={invalid} aria-describedby={describedBy} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}/><div><small>{file?"Assinatura capturada.":"Use o ponteiro, toque ou a alternativa por teclado."}</small><button type="button" onClick={clear} disabled={!file&&!typed}>Limpar assinatura</button></div><div className="signature-alternative"><label htmlFor={id+"-typed"}>Alternativa por teclado</label><div><input id={id+"-typed"} value={typed} onChange={event=>setTyped(event.target.value)} placeholder="Digite seu nome completo"/><button type="button" onClick={signName} disabled={!typed.trim()}>Registrar nome</button></div></div></div>
}
