/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import {type DragEvent,type PointerEvent,useEffect,useMemo,useRef,useState} from "react";
import {api,json} from "@/app/lib/api";
import {Icons,Notice} from "./DesignSystem";

type Field={id:string;type:string;label:string;description?:string;required?:boolean;options?:string[]};
type Section={id:string;title:string;description?:string;fields:Field[]};
type PublishedForm={id:string;name:string;description?:string;versionId:string;version:number;definition:{sections:Section[]}};
type UploadSession={fileId:string;objectKey:string;uploadUrl:string;expiresInSeconds:number};
type FileAnswer={fileId:string;objectKey:string;originalName:string;contentType:string};
type Answer=string|number|boolean|string[]|FileAnswer|null;
const passiveTypes=["heading","instructions"];
const fieldIcons:Record<string,typeof Icons.fieldText>={text:Icons.fieldText,textarea:Icons.fieldLongText,number:Icons.fieldNumber,date:Icons.fieldDate,time:Icons.fieldTime,select:Icons.fieldSelect,multiselect:Icons.fieldMultiSelect,checkbox:Icons.fieldCheckbox,photo:Icons.fieldPhoto,signature:Icons.fieldSignature};

export default function FormRunner({tenantId,formId}:{tenantId:string;formId:string}){
 const[form,setForm]=useState<PublishedForm>(),[answers,setAnswers]=useState<Record<string,Answer>>({}),[files,setFiles]=useState<Record<string,File>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[submitted,setSubmitted]=useState(false),[sectionIndex,setSectionIndex]=useState(0),[reviewing,setReviewing]=useState(false),[completedSections,setCompletedSections]=useState<string[]>([]),[announcement,setAnnouncement]=useState(""),[submitPhase,setSubmitPhase]=useState("");
 const submissionId=useRef(crypto.randomUUID()),submissionCreated=useRef(false),revision=useRef(0),uploadedFiles=useRef<Record<string,{file:File;answer:FileAnswer}>>({});
 useEffect(()=>{api<PublishedForm>("tenants/"+tenantId+"/forms/"+formId+"/published").then(setForm).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[tenantId,formId]);
 const sections=form?.definition.sections??[],currentSection=sections[sectionIndex];
 const interactiveFields=sections.flatMap(section=>section.fields).filter(field=>!passiveTypes.includes(field.type));
 const answeredCount=interactiveFields.filter(field=>hasValue(field,answers[field.id],files[field.id])).length;
 const progress=interactiveFields.length?Math.round(answeredCount/interactiveFields.length*100):100;

 function markChanged(fieldId:string){const section=sections.find(item=>item.fields.some(field=>field.id===fieldId));if(section)setCompletedSections(current=>current.filter(id=>id!==section.id))}
 function setAnswer(id:string,value:Answer){setAnswers(current=>({...current,[id]:value}));setErrors(current=>({...current,[id]:""}));markChanged(id)}
 function setFile(fieldId:string,file?:File){delete uploadedFiles.current[fieldId];setFiles(current=>file?{...current,[fieldId]:file}:Object.fromEntries(Object.entries(current).filter(([id])=>id!==fieldId)));setErrors(current=>({...current,[fieldId]:""}));markChanged(fieldId)}
 function focusField(fieldId:string){requestAnimationFrame(()=>requestAnimationFrame(()=>document.getElementById("field-"+fieldId)?.focus()))}
 function validateFields(fields:Field[]){const next:Record<string,string>={};for(const field of fields){if(field.required&&!passiveTypes.includes(field.type)&&!hasValue(field,answers[field.id],files[field.id]))next[field.id]="Este campo é obrigatório."}const ids=new Set(fields.map(field=>field.id));setErrors(current=>({...Object.fromEntries(Object.entries(current).filter(([id])=>!ids.has(id))),...next}));return next}
 function validateSection(index:number){const section=sections[index];if(!section)return false;const next=validateFields(section.fields);if(Object.keys(next).length){setAnnouncement("Revise os campos obrigatórios desta seção.");focusField(Object.keys(next)[0]);return false}setCompletedSections(current=>current.includes(section.id)?current:[...current,section.id]);return true}
 function scrollTop(smooth=false){window.scrollTo({top:0,behavior:smooth&&!window.matchMedia("(prefers-reduced-motion: reduce)").matches?"smooth":"auto"})}
 function continueForm(){if(!validateSection(sectionIndex))return;if(sectionIndex===sections.length-1){setReviewing(true);setAnnouncement("Revise suas respostas antes do envio.");scrollTop(true);return}const next=sectionIndex+1;setSectionIndex(next);setAnnouncement("Seção "+(next+1)+" de "+sections.length+".");scrollTop()}
 function previousSection(){if(sectionIndex===0)return;setSectionIndex(current=>current-1);scrollTop()}
 function openSection(index:number){setReviewing(false);setSectionIndex(index);setAnnouncement("Seção "+(index+1)+" de "+sections.length+".");scrollTop()}
 function startReview(){const next=validateFields(interactiveFields);if(Object.keys(next).length){const invalidId=Object.keys(next)[0],index=sections.findIndex(section=>section.fields.some(field=>field.id===invalidId));setReviewing(false);setSectionIndex(Math.max(0,index));setAnnouncement("Existem campos obrigatórios que precisam ser revisados.");focusField(invalidId);return false}setCompletedSections(sections.map(section=>section.id));setReviewing(true);return true}
 async function upload(field:Field,file:File){if(file.size>20*1024*1024)throw new Error("O arquivo de "+field.label+" ultrapassa 20 MB.");const session=await api<UploadSession>("tenants/"+tenantId+"/files/upload-sessions",json("POST",{formId,submissionId:submissionId.current,fieldId:field.id,originalName:file.name,contentType:file.type||"application/octet-stream",sizeBytes:file.size}));const sent=await fetch(session.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type||"application/octet-stream"},body:file});if(!sent.ok)throw new Error("Não foi possível enviar o arquivo de "+field.label+".");await api("tenants/"+tenantId+"/files/"+session.fileId+"/complete",json("POST",{formId}));return{fileId:session.fileId,objectKey:session.objectKey,originalName:file.name,contentType:file.type||"application/octet-stream"}}
 async function submit(){if(!form||!startReview())return;setSubmitting(true);setError("");try{const finalAnswers={...answers};let newlyCreated=false;if(!submissionCreated.current){setSubmitPhase("Salvando resposta...");await api("tenants/"+tenantId+"/submissions",json("POST",{id:submissionId.current,formId,formVersionId:form.versionId,answers:finalAnswers,clientCreatedAt:new Date().toISOString()}));submissionCreated.current=true;newlyCreated=true}const attachmentFields=sections.flatMap(section=>section.fields).filter(field=>["photo","signature"].includes(field.type)&&files[field.id]);for(const[index,field]of attachmentFields.entries()){const selectedFile=files[field.id],cached=uploadedFiles.current[field.id];if(cached?.file===selectedFile){finalAnswers[field.id]=cached.answer;continue}setSubmitPhase("Enviando anexo "+(index+1)+" de "+attachmentFields.length+"...");const answer=await upload(field,selectedFile);uploadedFiles.current[field.id]={file:selectedFile,answer};finalAnswers[field.id]=answer}if(attachmentFields.length||!newlyCreated){setSubmitPhase("Atualizando resposta...");await api("tenants/"+tenantId+"/submissions/"+submissionId.current,json("PATCH",{formId,revision:revision.current,answers:finalAnswers}));revision.current++}setSubmitPhase("Finalizando resposta...");await api("tenants/"+tenantId+"/submissions/"+submissionId.current+"/complete",json("POST",{formId,revision:revision.current,answers:finalAnswers}));setSubmitted(true)}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível enviar a resposta.");setAnnouncement("O envio falhou. Suas respostas foram preservadas para uma nova tentativa.")}finally{setSubmitting(false);setSubmitPhase("")}} if(loading)return <div className="center-state" role="status" aria-live="polite"><span className="loader"/><p>Carregando formulário...</p></div>;
 if(!form)return <div className="page"><Notice tone="danger">{error||"Formulário publicado não encontrado."}</Notice><Link className="button secondary" href="/app/formularios">Voltar aos formulários</Link></div>;
 if(submitted)return <div className="page runner-success" role="status" aria-live="polite"><span className="runner-success-icon"><Icons.check/></span><span className="eyebrow">Checklist concluído</span><h1>Resposta enviada</h1><p>O formulário <strong>{form.name}</strong> foi concluído e já está disponível no histórico de respostas.</p><div><Link className="button primary" href="/app/formularios">Voltar aos formulários</Link><Link className="button secondary" href="/app/respostas">Ver respostas</Link></div></div>;

 return <div className="page form-runner">
  <span className="sr-only" aria-live="polite">{announcement||submitPhase}</span>
  <header className="runner-hero"><div><span className="eyebrow">Formulário publicado · versão {form.version}</span><h1>{form.name}</h1><p>{form.description||"Preencha os campos abaixo e envie quando concluir."}</p></div><Link className="button secondary" href="/app/formularios">Sair do formulário</Link></header>
  <section className="runner-progress" aria-label="Progresso do formulário"><div className="runner-progress-copy"><div><span>{reviewing?"Revisão final":"Seção "+(sectionIndex+1)+" de "+sections.length}</span><strong>{progress}% preenchido</strong></div><div className="progress-track" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress} aria-label="Campos preenchidos"><span style={{width:progress+"%"}}/></div></div><ol>{sections.map((section,index)=>{const hasError=section.fields.some(field=>errors[field.id]),complete=completedSections.includes(section.id);return <li key={section.id}><button type="button" className={index===sectionIndex&&!reviewing?"active":hasError?"error":complete?"complete":""} onClick={()=>openSection(index)} aria-current={index===sectionIndex&&!reviewing?"step":undefined}><span>{complete&&!hasError?<Icons.check/>:String(index+1).padStart(2,"0")}</span><small>{section.title}</small></button></li>})}<li><button type="button" className={reviewing?"active":""} onClick={()=>{if(startReview())scrollTop()}} aria-current={reviewing?"step":undefined}><span><Icons.eye/></span><small>Revisão</small></button></li></ol></section>
  {error&&<Notice tone="danger" title="Não foi possível concluir">{error} Tente novamente; suas respostas continuam nesta tela.</Notice>}
  <form onSubmit={event=>{event.preventDefault();if(reviewing)void submit();else continueForm()}}>
   {!reviewing&&currentSection&&<section className="runner-section" aria-labelledby={"section-"+currentSection.id}><header><span>{String(sectionIndex+1).padStart(2,"0")}</span><div><span className="eyebrow">Etapa do checklist</span><h2 id={"section-"+currentSection.id}>{currentSection.title}</h2>{currentSection.description&&<p>{currentSection.description}</p>}</div></header>{currentSection.fields.some(field=>errors[field.id])&&<div className="runner-error-summary" role="alert"><Icons.warning/><div><strong>Revise esta seção</strong><span>Preencha os campos obrigatórios indicados abaixo.</span></div></div>}<div className="runner-fields">{currentSection.fields.map(field=><RunnerField key={field.id} field={field} value={answers[field.id]} file={files[field.id]} error={errors[field.id]} onValue={value=>setAnswer(field.id,value)} onFile={file=>setFile(field.id,file)}/>)}</div></section>}
   {reviewing&&<Review form={form} answers={answers} files={files} onEdit={openSection}/>}
   <div className="runner-navigation" aria-live="polite"><div>{!reviewing&&sectionIndex>0&&<button type="button" className="secondary" onClick={previousSection}><Icons.arrowLeft/>Voltar</button>}{reviewing&&<button type="button" className="secondary" onClick={()=>openSection(sections.length-1)}><Icons.arrowLeft/>Voltar para edição</button>}</div><div className="runner-navigation-copy"><small>{reviewing?"Confira todas as informações antes de registrar.":"As respostas são mantidas enquanto esta página permanecer aberta."}</small>{reviewing?<button className="primary" disabled={submitting}><Icons.send/>{submitting?submitPhase||"Enviando...":"Enviar resposta"}</button>:<button className="primary">{sectionIndex===sections.length-1?<><Icons.eye/>Revisar respostas</>:<>Continuar<Icons.arrowRight/></>}</button>}</div></div>
  </form>
 </div>;
}

function RunnerField({field,value,file,error,onValue,onFile}:{field:Field;value?:Answer;file?:File;error?:string;onValue:(value:Answer)=>void;onFile:(file?:File)=>void}){
 if(field.type==="heading")return <div className="runner-heading"><span><Icons.fieldHeading/></span><div><h3>{field.label}</h3>{field.description&&<p>{field.description}</p>}</div></div>;
 if(field.type==="instructions")return <div className="runner-instructions"><Icons.clipboard/><div><strong>{field.label}</strong>{field.description&&<p>{field.description}</p>}</div></div>;
 const id="field-"+field.id,errorId=id+"-error",helpId=id+"-help",describedBy=[field.description?helpId:"",error?errorId:""].filter(Boolean).join(" ")||undefined;
 const FieldIcon=fieldIcons[field.type]??Icons.fieldText;
 const label=<span className="runner-label"><span className="runner-field-icon" aria-hidden="true"><FieldIcon/></span><span><strong>{field.label}</strong>{field.required&&<small>Obrigatório</small>}</span></span>;
 let control;
 if(field.type==="textarea")control=<textarea id={id} value={String(value??"")} onChange={event=>onValue(event.target.value)} aria-invalid={!!error} aria-describedby={describedBy} rows={5}/>;
 else if(field.type==="select")control=<select id={id} value={String(value??"")} onChange={event=>onValue(event.target.value)} aria-invalid={!!error} aria-describedby={describedBy}><option value="">Selecione uma opção</option>{(field.options??[]).map(option=><option key={option}>{option}</option>)}</select>;
 else if(field.type==="multiselect")control=<fieldset id={id} tabIndex={-1} className="runner-choice-group" aria-invalid={!!error} aria-describedby={describedBy}><legend className="sr-only">{field.label}</legend>{(field.options??[]).map(option=>{const checked=Array.isArray(value)&&value.includes(option);return <label className={"runner-choice "+(checked?"selected":"")} key={option}><input type="checkbox" checked={checked} onChange={event=>onValue(event.target.checked?[...(Array.isArray(value)?value:[]),option]:(Array.isArray(value)?value:[]).filter(item=>item!==option))}/><span><Icons.check/>{option}</span></label>})}</fieldset>;
 else if(field.type==="checkbox")control=<label className={"runner-check "+(value===true?"selected":"")}><input id={id} type="checkbox" checked={value===true} onChange={event=>onValue(event.target.checked)} aria-invalid={!!error} aria-describedby={describedBy}/><span><Icons.check/><span>{field.label}<small>{field.required?"Obrigatório · ":""}{field.description||"Marque para confirmar"}</small></span></span></label>;
 else if(field.type==="photo")control=<PhotoInput id={id} field={field} file={file} invalid={!!error} describedBy={describedBy} onFile={onFile}/>;
 else if(field.type==="signature")control=<SignaturePad id={id} file={file} invalid={!!error} describedBy={describedBy} onFile={onFile}/>;
 else control=<input id={id} type={field.type==="number"?"number":field.type==="date"?"date":field.type==="time"?"time":"text"} value={String(value??"")} onChange={event=>onValue(event.target.value)} aria-invalid={!!error} aria-describedby={describedBy}/>;
 return <div className={"runner-field runner-field-"+field.type+" "+(error?"has-error":"")}>{field.type!=="checkbox"&&<label htmlFor={field.type==="multiselect"?undefined:field.type==="photo"?id+"-input":id}>{label}</label>}{control}{field.description&&field.type!=="checkbox"&&<small id={helpId} className="field-help">{field.description}</small>}{field.type==="signature"&&<small className="field-help">Assine no quadro usando mouse, caneta ou toque.</small>}{error&&<small id={errorId} className="field-error" role="alert"><Icons.warning/>{error}</small>}</div>;
}

function PhotoInput({id,field,file,invalid,describedBy,onFile}:{id:string;field:Field;file?:File;invalid:boolean;describedBy?:string;onFile:(file?:File)=>void}){
 const input=useRef<HTMLInputElement>(null),preview=useObjectUrl(file),[localError,setLocalError]=useState(""),[dragging,setDragging]=useState(false);
 function choose(candidate?:File){setDragging(false);if(!candidate)return;if(!candidate.type.startsWith("image/")){setLocalError("Escolha um arquivo de imagem.");return}if(candidate.size>20*1024*1024){setLocalError("A imagem deve ter no máximo 20 MB.");return}setLocalError("");onFile(candidate)}
 function drop(event:DragEvent<HTMLDivElement>){event.preventDefault();choose(event.dataTransfer.files?.[0])}
 function clear(){if(input.current)input.current.value="";setLocalError("");onFile(undefined)}
 return <div id={id} tabIndex={-1} className={"photo-capture "+(file?"has-file ":"")+(dragging?"is-dragging":"")} onDragEnter={event=>{event.preventDefault();setDragging(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={drop}>
  <input className="sr-only" ref={input} id={id+"-input"} type="file" accept="image/*" capture="environment" onChange={event=>choose(event.target.files?.[0])} aria-invalid={invalid||!!localError} aria-describedby={describedBy}/>
  {file&&preview?<div className="photo-preview"><img src={preview} alt={"Pré-visualização de "+field.label}/><div><span className="status-badge status-active"><Icons.check/>Imagem pronta</span><strong>{file.name}</strong><small>{formatBytes(file.size)}</small></div></div>:<div className="photo-placeholder"><span><Icons.camera/></span><strong>Tire ou escolha uma foto</strong><small>Imagem JPG, PNG ou HEIC com até 20 MB.</small></div>}
  <div className="photo-actions"><label className="button primary" htmlFor={id+"-input"}><Icons.camera/>{file?"Substituir foto":"Tirar ou escolher foto"}</label>{file&&<button type="button" className="danger" onClick={clear}><Icons.delete/>Remover</button>}</div>
  {localError&&<small className="field-error" role="alert"><Icons.warning/>{localError}</small>}
 </div>;
}

function SignaturePad({id,file,invalid,describedBy,onFile}:{id:string;file?:File;invalid:boolean;describedBy?:string;onFile:(file?:File)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),[typed,setTyped]=useState("");
 function point(event:PointerEvent<HTMLCanvasElement>){const element=canvas.current!,rect=element.getBoundingClientRect();return{x:(event.clientX-rect.left)*(element.width/rect.width),y:(event.clientY-rect.top)*(element.height/rect.height)}}
 function start(event:PointerEvent<HTMLCanvasElement>){const element=canvas.current!,context=element.getContext("2d");if(!context)return;event.preventDefault();element.setPointerCapture(event.pointerId);const p=point(event);context.beginPath();context.moveTo(p.x,p.y);context.lineWidth=4;context.lineCap="round";context.lineJoin="round";context.strokeStyle=getComputedStyle(element).getPropertyValue("--text").trim()||"#163843";drawing.current=true}
 function move(event:PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;event.preventDefault();const context=canvas.current?.getContext("2d");if(!context)return;const p=point(event);context.lineTo(p.x,p.y);context.stroke()}
 function finish(event:PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;drawing.current=false;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);canvas.current?.toBlob(blob=>{if(blob)onFile(new File([blob],"assinatura.png",{type:"image/png"}))},"image/png")}
 function signName(){const element=canvas.current,context=element?.getContext("2d");if(!element||!context||!typed.trim())return;context.clearRect(0,0,element.width,element.height);context.fillStyle=getComputedStyle(element).getPropertyValue("--text").trim()||"#163843";context.font="italic 52px sans-serif";context.fillText(typed.trim(),42,140);element.toBlob(blob=>{if(blob)onFile(new File([blob],"assinatura.png",{type:"image/png"}))},"image/png")}
 function clear(){const element=canvas.current,context=element?.getContext("2d");if(element&&context)context.clearRect(0,0,element.width,element.height);setTyped("");onFile(undefined)}
 return <div className={"signature-pad "+(file?"is-signed":"")}><div className="signature-status"><span><Icons.fieldSignature/></span><div><strong>{file?"Assinatura registrada":"Área de assinatura"}</strong><small>{file?"Você pode limpar e assinar novamente.":"Use mouse, caneta, toque ou a alternativa por teclado."}</small></div></div><canvas id={id} ref={canvas} width="900" height="240" tabIndex={0} aria-label="Área para desenhar a assinatura" aria-invalid={invalid} aria-describedby={describedBy} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}/><div className="signature-toolbar"><small>{file?<><Icons.check/>Capturada com sucesso</>:"Assine dentro da área acima."}</small><button type="button" onClick={clear} disabled={!file&&!typed}>{file?"Refazer assinatura":"Limpar"}</button></div><div className="signature-alternative"><label htmlFor={id+"-typed"}>Alternativa por teclado</label><div><input id={id+"-typed"} value={typed} onChange={event=>setTyped(event.target.value)} placeholder="Digite seu nome completo"/><button type="button" onClick={signName} disabled={!typed.trim()}>Registrar nome</button></div></div></div>;
}

function Review({form,answers,files,onEdit}:{form:PublishedForm;answers:Record<string,Answer>;files:Record<string,File>;onEdit:(index:number)=>void}){
 return <section className="runner-review"><header><span className="runner-review-icon"><Icons.clipboard/></span><div><span className="eyebrow">Última etapa</span><h2>Revise suas respostas</h2><p>Confira as informações antes de registrar este checklist no histórico.</p></div></header><div className="review-sections">{form.definition.sections.map((section,index)=><article key={section.id}><header><div><span>Seção {String(index+1).padStart(2,"0")}</span><h3>{section.title}</h3></div><button type="button" onClick={()=>onEdit(index)}><Icons.edit/>Editar</button></header><dl>{section.fields.filter(field=>!passiveTypes.includes(field.type)).map(field=><div key={field.id}><dt>{field.label}{field.required&&<small>Obrigatório</small>}</dt><dd>{field.type==="photo"&&files[field.id]?<ReviewPhoto file={files[field.id]} label={field.label}/>:field.type==="signature"&&files[field.id]?<span className="review-captured"><Icons.check/>Assinatura capturada</span>:formatAnswer(answers[field.id])}</dd></div>)}</dl></article>)}</div></section>;
}
function ReviewPhoto({file,label}:{file:File;label:string}){const url=useObjectUrl(file);return <span className="review-photo">{url&&<img src={url} alt={"Miniatura de "+label}/>}<span><strong>{file.name}</strong><small>{formatBytes(file.size)}</small></span></span>}
function useObjectUrl(file?:File){const url=useMemo(()=>file?URL.createObjectURL(file):"",[file]);useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);return url}
function hasValue(field:Field,value:Answer|undefined,file?:File){if(["photo","signature"].includes(field.type))return!!file;if(field.type==="checkbox")return value===true;return value!==undefined&&value!==null&&value!==""&&(!Array.isArray(value)||value.length>0)}
function formatAnswer(value:Answer|undefined){if(value===undefined||value===null||value===""||Array.isArray(value)&&!value.length)return <span className="review-empty">Não informado</span>;if(Array.isArray(value))return value.join(", ");if(typeof value==="boolean")return value?"Confirmado":"Não confirmado";if(typeof value==="object")return value.originalName;return String(value)}
function formatBytes(bytes:number){if(bytes<1024*1024)return Math.max(1,Math.round(bytes/1024))+" KB";return(bytes/1024/1024).toFixed(1)+" MB"}
