/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {FormEvent,useEffect,useState} from "react";
import FormEditor from "./FormEditor";
import AccessPanel from "./AccessPanel";
import ProfileSettings from "./ProfileSettings";
import ForcedPasswordModal from "./ForcedPasswordModal";
import {Dialog,EmptyState,Icons,Notice,PageHeader,StatusBadge} from "./DesignSystem";
import {api,formatDate,json} from "@/app/lib/api";
type Me={id:string;email:string;displayName:string;platformAdmin:boolean;mustChangePassword:boolean};
type Tenant={tenantId:string;name:string;slug:string;membershipId:string;type:string;status:string};
type Context={tenant:any;membershipType:string;platformAdmin:boolean;permissions:string[]};
const tenantNav=[
 {href:"/app",label:"Visão geral",icon:Icons.home},
 {href:"/app/formularios",label:"Formulários",icon:Icons.forms,permission:"FORM_VIEW"},
 {href:"/app/respostas",label:"Respostas",icon:Icons.clipboard,permission:"SUBMISSION_VIEW"},
 {href:"/app/equipe",label:"Equipe",icon:Icons.people,permission:"USER_VIEW"},
 {href:"/app/acessos",label:"Acessos",icon:Icons.shield,permission:"TENANT_MANAGE"},
 {href:"/app/auditoria",label:"Auditoria",icon:Icons.key,permission:"TENANT_MANAGE"},
 {href:"/app/configuracoes",label:"Configurações",icon:Icons.settings},
];
const adminNav=[{href:"/admin",label:"Visão geral",icon:Icons.home},{href:"/admin/tenants",label:"Tenants",icon:Icons.building},{href:"/admin/usuarios",label:"Usuários",icon:Icons.person}];
export default function Workspace({adminMode=false}:{adminMode?:boolean}){
 const path=usePathname(),[me,setMe]=useState<Me>(),[tenants,setTenants]=useState<Tenant[]>([]),[tenantId,setTenantId]=useState(""),[context,setContext]=useState<Context>(),[loading,setLoading]=useState(true),[error,setError]=useState(""),[menu,setMenu]=useState(false),[theme,setTheme]=useState(()=>typeof window==="undefined"?"light":localStorage.getItem("inspecteam_theme")??"light");
 useEffect(()=>{document.documentElement.dataset.theme=theme;Promise.all([api<Me>("me"),api<Tenant[]>("tenants")]).then(([m,t])=>{setMe(m);setTenants(t);const chosen=localStorage.getItem("inspecteam_tenant");setTenantId(t.some(x=>x.tenantId===chosen)?chosen!:t[0]?.tenantId??"")}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!tenantId||adminMode)return;api<Context>(`tenants/${tenantId}/context`).then(setContext).catch(e=>setError(e.message))},[tenantId,adminMode]);
 function selectTenant(id:string){localStorage.setItem("inspecteam_tenant",id);setTenantId(id);setContext(undefined)}
 function toggleTheme(){const next=theme==="light"?"dark":"light";setTheme(next);localStorage.setItem("inspecteam_theme",next);document.documentElement.dataset.theme=next}
 async function logout(){await fetch("/gateway/auth/logout",{method:"POST"});window.location.assign("/login")}
 const can=(p?:string)=>!p||!!context&&(context.membershipType==="OWNER"||context.platformAdmin||context.permissions.includes(p));
 const nav=(adminMode?adminNav:tenantNav).filter(item=>adminMode||can(item.permission));
 const activeLabel=nav.find(item=>item.href===path||item.href!=="/app"&&path.startsWith(item.href))?.label??"InspecTeam";
 if(loading)return <div className="center-state"><span className="loader"/><p>Preparando seu ambiente...</p></div>;
 if(error&&!me)return <div className="center-state"><Icons.warning/><h1>Não foi possível abrir a aplicação</h1><p>{error}</p><Link className="button primary" href="/login">Voltar ao login</Link></div>;
 return <div className="app-shell">
  <aside className={`sidebar ${menu?"open":""}`} aria-label="Navegação principal"><div className="sidebar-head"><div className="brand-lockup"><span className="brand-mark">IT</span>InspecTeam</div></div>
   {!adminMode&&<div className="tenant-switcher"><label>Empresa ativa<select value={tenantId} onChange={e=>selectTenant(e.target.value)}>{tenants.map(t=><option key={t.tenantId} value={t.tenantId}>{t.name}</option>)}</select></label></div>}
   <span className="nav-group-label">{adminMode?"Plataforma":"Operação"}</span><nav>{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className={path===href||href!=="/app"&&path.startsWith(href)?"active":""} onClick={()=>setMenu(false)}><Icon/>{label}</Link>)}</nav>
   {me?.platformAdmin&&<Link className="admin-switch" href={adminMode?"/app":"/admin"}>{adminMode?"Voltar à empresa":"Administração global"}</Link>}
   <div className="sidebar-user"><span className="avatar">{me?.displayName?.slice(0,2).toUpperCase()}</span><div><strong>{me?.displayName}</strong><small>{adminMode?"Administrador global":context?.membershipType==="OWNER"?"Proprietário":"Membro"}</small></div><button className="icon-button" onClick={logout} aria-label="Sair"><Icons.signOut/></button></div>
  </aside>
  <main className="workspace"><header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setMenu(!menu)} aria-label="Abrir navegação"><Icons.navigation/></button><div className="breadcrumbs"><span>{adminMode?"Administração global":"Gestão da empresa"}</span><span>/</span><strong>{activeLabel}</strong></div><div className="topbar-actions"><button className="icon-button" onClick={toggleTheme} aria-label={theme==="light"?"Ativar tema escuro":"Ativar tema claro"}>{theme==="light"?"◐":"◑"}</button><div className="topbar-user"><span className="avatar">{me?.displayName?.slice(0,2).toUpperCase()}</span><div><strong>{me?.displayName}</strong></div></div></div></header>
   {adminMode&&<div className="context-banner"><Icons.shield/><span><strong>Administração global.</strong> Operações sensíveis são registradas para auditoria.</span></div>}
   {!adminMode&&context?.platformAdmin&&<div className="context-banner"><Icons.warning/><span><strong>Acesso elevado.</strong> Você está atuando neste tenant como suporte da plataforma.</span></div>}
   {error&&<div className="page"><Notice tone="danger">{error}</Notice></div>}
   {adminMode?<AdminContent path={path}/>:tenantId&&context?<TenantContent path={path} tenantId={tenantId} context={context}/>:<EmptyState title="Nenhuma empresa disponível" description="Selecione ou cadastre uma empresa para continuar."/>}
  </main>{me?.mustChangePassword&&<ForcedPasswordModal onChanged={()=>api<Me>("me").then(setMe)}/>}</div>
}
function TenantContent({path,tenantId,context}:{path:string;tenantId:string;context:Context}){if(path==="/app/formularios/novo")return <FormEditor tenantId={tenantId}/>;if(path.startsWith("/app/formularios/"))return <FormEditor tenantId={tenantId} id={path.split("/").pop()}/>;if(path==="/app/formularios")return <Forms tenantId={tenantId}/>;if(path.startsWith("/app/respostas"))return <Submissions tenantId={tenantId} detailId={path.split("/")[3]}/>;if(path==="/app/equipe")return <Team tenantId={tenantId}/>;if(path==="/app/acessos")return <AccessPanel tenantId={tenantId}/>;if(path==="/app/auditoria")return <Audit tenantId={tenantId}/>;if(path==="/app/configuracoes")return <Settings tenantId={tenantId} context={context}/>;return <Overview tenantId={tenantId} context={context}/>}
function Metric({label,value}:{label:string;value:any}){return <article className="metric"><span>{label}</span><strong>{value??"—"}</strong></article>}
function Overview({tenantId,context}:{tenantId:string;context:Context}){const [data,setData]=useState<any>();useEffect(()=>{api(`tenants/${tenantId}/dashboard`).then(setData)},[tenantId]);return <div className="page"><PageHeader eyebrow="Visão geral" title={context.tenant.name} description="Acompanhe a operação e acesse rapidamente as tarefas que precisam de atenção."/><section className="metrics" aria-label="Indicadores da operação"><Metric label="Formulários" value={data?.forms}/><Metric label="Respostas concluídas" value={data?.completedSubmissions}/><Metric label="Pessoas ativas" value={data?.activeMembers}/><Metric label="Rascunhos" value={data?.drafts}/></section><section className="feature-panel"><div><span className="eyebrow">Próxima etapa</span><h2>Estruture sua próxima inspeção</h2><p>Crie o checklist, publique uma versão estável e defina quem poderá utilizá-lo em campo.</p><Link className="button primary" href="/app/formularios/novo"><Icons.add/>Criar formulário</Link></div><div className="workflow"><span>01 · Criar estrutura</span><span>02 · Validar campos</span><span>03 · Publicar versão</span><span>04 · Acompanhar respostas</span></div></section></div>}
function Forms({tenantId}:{tenantId:string}){const [items,setItems]=useState<any[]>([]),[error,setError]=useState(""),[target,setTarget]=useState<any>();const load=()=>api<any[]>(`tenants/${tenantId}/forms`).then(setItems).catch(e=>setError(e.message));useEffect(()=>{void load()},[tenantId]);async function change(){const f=target;setTarget(undefined);await api(`tenants/${tenantId}/forms/${f.id}/${f.status!=="ARCHIVED"?"archive":"restore"}`,{method:"POST"});load()}return <div className="page"><PageHeader eyebrow="Operação" title="Formulários" description="Crie, versione e distribua checklists para a equipe." action={<Link className="button primary" href="/app/formularios/novo"><Icons.add/>Novo formulário</Link>}/>{error&&<Notice tone="danger">{error}</Notice>}<div className="table-card"><div className="table-scroll"><table><thead><tr><th>Formulário</th><th>Status</th><th>Versão</th><th>Atualizado</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{items.map(f=><tr key={f.id}><td><strong>{f.name}</strong><small>{f.description||"Sem descrição"}</small></td><td><StatusBadge status={f.status}/></td><td>{f.publishedVersion?`v${f.publishedVersion}`:"Não publicado"}</td><td>{formatDate(f.updatedAt)}</td><td className="row-actions"><Link href={`/app/formularios/${f.id}`}><Icons.edit/>Editar</Link><button onClick={()=>setTarget(f)}><Icons.archive/>{f.status==="ARCHIVED"?"Restaurar":"Arquivar"}</button></td></tr>)}</tbody></table></div>{items.length===0&&<EmptyState title="Nenhum formulário" description="Comece criando o checklist da sua operação." action={<Link className="button primary" href="/app/formularios/novo">Criar primeiro formulário</Link>}/>}</div>{target&&<Dialog tone={target.status==="ARCHIVED"?"primary":"danger"} title={target.status==="ARCHIVED"?"Restaurar formulário?":"Arquivar formulário?"} description={target.status==="ARCHIVED"?"O formulário voltará a aparecer entre os itens ativos.":"O formulário será retirado da operação, mas seu histórico será preservado."} confirmLabel={target.status==="ARCHIVED"?"Restaurar":"Arquivar"} onClose={()=>setTarget(undefined)} onConfirm={change}/>}</div>}
function Submissions({tenantId,detailId}:{tenantId:string;detailId?:string}){const [forms,setForms]=useState<any[]>([]),[form,setForm]=useState(""),[items,setItems]=useState<any[]>([]),[detail,setDetail]=useState<any>();useEffect(()=>{api<any[]>(`tenants/${tenantId}/forms`).then(v=>{setForms(v);setForm(v[0]?.id??"")})},[tenantId]);useEffect(()=>{if(form)api<any[]>(`tenants/${tenantId}/submissions?formId=${form}`).then(setItems)},[form,tenantId]);useEffect(()=>{if(detailId&&form)api(`tenants/${tenantId}/submissions/${detailId}?formId=${form}`).then(setDetail)},[detailId,form,tenantId]);if(detail)return <div className="page"><PageHeader eyebrow="Respostas / Detalhe" title={`Resposta ${detail.id.slice(0,8)}`} description={`${detail.submittedByName} · ${formatDate(detail.submittedAt)}`} action={<Link className="button secondary" href="/app/respostas">Voltar</Link>}/><div className="detail-card">{Object.entries(detail.answers).map(([key,value])=><div key={key}><span>{key}</span><strong>{String(value)}</strong></div>)}</div></div>;return <div className="page"><PageHeader eyebrow="Operação de campo" title="Respostas" description="Consulte os registros enviados pela equipe e a versão utilizada."/><label className="filter">Formulário<select value={form} onChange={e=>setForm(e.target.value)}>{forms.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Identificador</th><th>Status</th><th>Revisão</th><th>Atualizado</th><th/></tr></thead><tbody>{items.map(s=><tr key={s.id}><td><strong>{s.id.slice(0,8)}</strong></td><td><StatusBadge status={s.status}/></td><td>{s.revision}</td><td>{formatDate(s.updatedAt)}</td><td className="row-actions"><Link href={`/app/respostas/${s.id}`}><Icons.eye/>Detalhes</Link></td></tr>)}</tbody></table></div>{items.length===0&&<EmptyState title="Nenhuma resposta" description="As inspeções concluídas aparecerão aqui."/>}</div></div>}
function Team({tenantId}:{tenantId:string}){const [users,setUsers]=useState<any[]>([]),[open,setOpen]=useState(false),[message,setMessage]=useState("");const load=()=>api<any[]>(`tenants/${tenantId}/users`).then(setUsers);useEffect(()=>{void load()},[tenantId]);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api(`tenants/${tenantId}/users`,json("POST",d));setOpen(false);setMessage("Pessoa adicionada. A senha temporária deverá ser alterada no primeiro acesso.");load()}async function toggle(u:any){await api(`tenants/${tenantId}/users/${u.membershipId}/status`,json("PATCH",{status:u.status==="ACTIVE"?"SUSPENDED":"ACTIVE"}));load()}return <div className="page"><PageHeader eyebrow="Pessoas" title="Equipe" description="Gerencie quem participa da operação e o estado de acesso de cada conta." action={<button className="primary" onClick={()=>setOpen(true)}><Icons.personAdd/>Adicionar pessoa</button>}/>{message&&<Notice tone="success">{message}</Notice>}<div className="cards-grid">{users.map(u=><article className="person-card" key={u.membershipId}><span className="avatar large">{u.displayName.slice(0,2).toUpperCase()}</span><div><h3>{u.displayName}</h3><p>{u.email}</p><StatusBadge status={u.membershipType}/></div>{!["OWNER","PLATFORM_ADMIN"].includes(u.membershipType)&&<button onClick={()=>toggle(u)}>{u.status==="ACTIVE"?"Suspender":"Ativar"}</button>}</article>)}</div>{!users.length&&<EmptyState icon={Icons.people} title="Equipe vazia" description="Adicione a primeira pessoa para começar a distribuir formulários."/>}{open&&<div className="modal-backdrop"><form className="modal small" onSubmit={add} role="dialog" aria-modal="true" aria-labelledby="add-person-title"><div><span className="eyebrow">Nova conta</span><h2 id="add-person-title">Adicionar pessoa</h2><p className="muted">Ela deverá criar uma nova senha no primeiro acesso.</p></div><label>Nome completo<input name="displayName" required autoFocus/></label><label>E-mail<input name="email" type="email" required/></label><label>Senha temporária<input name="temporaryPassword" type="password" minLength={10} required/></label><div className="dialog-actions"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">Adicionar pessoa</button></div></form></div>}</div>}
function Audit({tenantId}:{tenantId:string}){const [items,setItems]=useState<any[]>([]),[error,setError]=useState("");useEffect(()=>{api<any[]>(`tenants/${tenantId}/audit`).then(setItems).catch(e=>setError(e.message))},[tenantId]);return <div className="page"><PageHeader eyebrow="Governança" title="Auditoria" description="Histórico imutável das operações realizadas neste tenant."/>{error&&<Notice tone="danger">{error}</Notice>}<div className="table-card"><div className="table-scroll"><table><thead><tr><th>Data</th><th>Ação</th><th>Recurso</th><th>Responsável</th></tr></thead><tbody>{items.map(event=><tr key={event.id}><td>{formatDate(event.occurredAt||event.createdAt)}</td><td><strong>{event.action}</strong></td><td>{event.resourceType}<small>{event.resourceId}</small></td><td>{event.actorUserId?.slice(0,8)??"Sistema"}</td></tr>)}</tbody></table></div>{!items.length&&!error&&<EmptyState icon={Icons.key} title="Sem eventos registrados" description="As próximas operações auditáveis serão exibidas aqui."/>}</div></div>}
function Settings({tenantId,context}:{tenantId:string;context:Context}){const [message,setMessage]=useState("");async function tenant(e:FormEvent<HTMLFormElement>){e.preventDefault();await api(`tenants/${tenantId}`,json("PATCH",Object.fromEntries(new FormData(e.currentTarget))));setMessage("Dados da empresa atualizados.")}async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();await api("me/password",json("POST",Object.fromEntries(new FormData(e.currentTarget))));e.currentTarget.reset();setMessage("Senha alterada com segurança.")}return <div className="page"><PageHeader eyebrow="Preferências" title="Configurações" description="Atualize seu perfil, os dados da empresa e as credenciais de acesso."/>{message&&<Notice tone="success">{message}</Notice>}<div className="settings-profile"><ProfileSettings/></div><div className="split"><form className="panel" onSubmit={tenant}><h2>Empresa</h2><label>Nome<input name="name" defaultValue={context.tenant.name}/></label><label>Fuso horário<input name="timezone" defaultValue={context.tenant.timezone}/></label><button className="primary">Salvar empresa</button></form><form className="panel" onSubmit={password}><h2>Alterar senha</h2><label>Senha atual<input name="currentPassword" type="password" required/></label><label>Nova senha<input name="newPassword" type="password" minLength={10} required/></label><button className="primary">Alterar senha</button></form></div></div>}
function AdminContent({path}:{path:string}){if(path==="/admin/tenants")return <AdminTenants/>;if(path==="/admin/usuarios")return <AdminUsers/>;return <AdminOverview/>}
function AdminOverview(){const [data,setData]=useState<any>();useEffect(()=>{api("admin/overview").then(setData)},[]);return <div className="page"><PageHeader eyebrow="Plataforma" title="Administração global" description="Visão consolidada da saúde operacional do InspecTeam."/><section className="metrics"><Metric label="Tenants" value={data?.tenants}/><Metric label="Tenants ativos" value={data?.activeTenants}/><Metric label="Usuários" value={data?.users}/><Metric label="Respostas concluídas" value={data?.completedSubmissions}/></section><Notice tone="info" title="Rastreabilidade administrativa">Alterações de status, promoções e acessos elevados são registrados no banco de auditoria da plataforma.</Notice></div>}
function AdminTenants(){const [data,setData]=useState<any>({items:[]}),[query,setQuery]=useState("");const load=()=>api<any>(`admin/tenants?query=${encodeURIComponent(query)}`).then(setData);useEffect(()=>{void load()},[]);async function status(id:string,value:string){await api(`admin/tenants/${id}/status`,json("PATCH",{status:value}));load()}async function enter(t:any){await api(`admin/tenants/${t.id}/enter`,{method:"POST"});localStorage.setItem("inspecteam_tenant",t.id);window.location.assign("/app")}return <div className="page"><PageHeader eyebrow="Plataforma" title="Tenants" description="Consulte organizações, avalie a atividade e execute operações administrativas."/><div className="search"><Icons.search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Buscar nome ou identificador" aria-label="Buscar tenants"/><button onClick={load}>Buscar</button></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Tenant</th><th>Status</th><th>Membros</th><th>Formulários</th><th/></tr></thead><tbody>{data.items.map((t:any)=><tr key={t.id}><td><strong>{t.name}</strong><small>{t.slug}</small></td><td><StatusBadge status={t.status}/></td><td>{t.members}</td><td>{t.forms}</td><td className="row-actions"><button onClick={()=>enter(t)}><Icons.arrowRight/>Acessar</button><select aria-label={`Alterar status de ${t.name}`} value={t.status} onChange={e=>status(t.id,e.target.value)}><option value="ACTIVE">Ativo</option><option value="SUSPENDED">Suspenso</option><option value="ARCHIVED">Arquivado</option></select></td></tr>)}</tbody></table></div>{!data.items.length&&<EmptyState icon={Icons.building} title="Nenhum tenant encontrado" description="Ajuste a busca e tente novamente."/>}</div></div>}
function AdminUsers(){const [data,setData]=useState<any>({items:[]}),[query,setQuery]=useState("");const load=()=>api<any>(`admin/users?query=${encodeURIComponent(query)}`).then(setData);useEffect(()=>{void load()},[]);async function update(id:string,path:string,body:any){await api(`admin/users/${id}/${path}`,json(path==="platform-admin"?"PUT":"PATCH",body));load()}return <div className="page"><PageHeader eyebrow="Plataforma" title="Usuários" description="Gerencie contas, estados de acesso e administradores globais."/><div className="search"><Icons.search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Buscar nome ou e-mail" aria-label="Buscar usuários"/><button onClick={load}>Buscar</button></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Usuário</th><th>Status</th><th>Admin global</th><th/></tr></thead><tbody>{data.items.map((u:any)=><tr key={u.id}><td><strong>{u.displayName}</strong><small>{u.email}</small></td><td><StatusBadge status={u.status}/></td><td><label><input type="checkbox" checked={u.platformAdmin} onChange={e=>update(u.id,"platform-admin",{enabled:e.target.checked})}/><span className="sr-only">Administrador global</span></label></td><td className="row-actions"><button onClick={()=>update(u.id,"status",{status:u.status==="ACTIVE"?"SUSPENDED":"ACTIVE"})}>{u.status==="ACTIVE"?"Suspender":"Ativar"}</button></td></tr>)}</tbody></table></div>{!data.items.length&&<EmptyState icon={Icons.person} title="Nenhum usuário encontrado" description="Ajuste a busca e tente novamente."/>}</div></div>}
