/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars, react-hooks/exhaustive-deps */
"use client";
import Link from "next/link";import {usePathname} from "next/navigation";import {FormEvent,useEffect,useMemo,useState} from "react";import FormEditor from "./FormEditor";import AccessPanel from "./AccessPanel";import ProfileSettings from "./ProfileSettings";import ForcedPasswordModal from "./ForcedPasswordModal";import {api,formatDate,json} from "@/app/lib/api";
type Me={id:string;email:string;displayName:string;platformAdmin:boolean;mustChangePassword:boolean};type Tenant={tenantId:string;name:string;slug:string;membershipId:string;type:string;status:string};type Context={tenant:any;membershipType:string;platformAdmin:boolean;permissions:string[]};
const labels:Record<string,string>={FORM_VIEW:"Visualizar formulários",FORM_CREATE:"Criar formulários",FORM_EDIT:"Editar formulários",FORM_PUBLISH:"Publicar formulários",FORM_ARCHIVE:"Arquivar formulários",FORM_USE:"Preencher no aplicativo",FORM_MANAGE_ACCESS:"Gerenciar acessos",USER_VIEW:"Visualizar equipe",USER_CREATE:"Adicionar pessoas",USER_UPDATE:"Atualizar pessoas",USER_SUSPEND:"Suspender pessoas",SUBMISSION_VIEW:"Visualizar respostas",SUBMISSION_EXPORT:"Exportar respostas",TENANT_MANAGE:"Administrar empresa"};
export default function Workspace({adminMode=false}:{adminMode?:boolean}){
 const path=usePathname();const [me,setMe]=useState<Me>();const [tenants,setTenants]=useState<Tenant[]>([]);const [tenantId,setTenantId]=useState("");const [context,setContext]=useState<Context>();const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [menu,setMenu]=useState(false);
 useEffect(()=>{Promise.all([api<Me>("me"),api<Tenant[]>("tenants")]).then(([m,t])=>{setMe(m);setTenants(t);const chosen=localStorage.getItem("inspecteam_tenant");setTenantId(t.some(x=>x.tenantId===chosen)?chosen!:t[0]?.tenantId??"")}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!tenantId||adminMode)return;api<Context>(`tenants/${tenantId}/context`).then(setContext).catch(e=>setError(e.message))},[tenantId,adminMode]);
 function selectTenant(id:string){localStorage.setItem("inspecteam_tenant",id);setTenantId(id);setContext(undefined)}
 async function logout(){await fetch("/gateway/auth/logout",{method:"POST"});location.href="/login"}
 const can=(p:string)=>!!context&&(context.membershipType==="OWNER"||context.platformAdmin||context.permissions.includes(p));
 const nav=adminMode?[['/admin','Visão geral'],['/admin/tenants','Tenants'],['/admin/usuarios','Usuários']]:[['/app','Visão geral'],['/app/formularios','Formulários'],['/app/respostas','Respostas'],['/app/equipe','Equipe'],['/app/acessos','Acessos'],['/app/configuracoes','Configurações']];
 if(loading)return <div className="center-state"><span className="loader"/><p>Preparando seu espaço...</p></div>;
 if(error&&!me)return <div className="center-state"><h1>Não foi possível abrir a aplicação</h1><p>{error}</p><Link className="primary button" href="/login">Voltar ao login</Link></div>;
 return <div className="app-shell"><aside className={`sidebar ${menu?'open':''}`}><div className="brand-lockup"><span className="brand-mark">I</span>InspecTeam</div>{!adminMode&&<label className="tenant-select"><span>Empresa ativa</span><select value={tenantId} onChange={e=>selectTenant(e.target.value)}>{tenants.map(t=><option key={t.tenantId} value={t.tenantId}>{t.name}</option>)}</select></label>}<nav>{nav.map(([href,label])=>{if(!adminMode&&label==='Formulários'&&!can('FORM_VIEW'))return null;if(!adminMode&&label==='Respostas'&&!can('SUBMISSION_VIEW'))return null;if(!adminMode&&label==='Equipe'&&!can('USER_VIEW'))return null;if(!adminMode&&label==='Acessos'&&!can('TENANT_MANAGE'))return null;return <Link key={href} href={href} className={path===href||href!=='/app'&&path.startsWith(href)?'active':''} onClick={()=>setMenu(false)}><span className="nav-dot"/>{label}</Link>})}</nav>{me?.platformAdmin&&<Link className="admin-switch" href={adminMode?"/app":"/admin"}>{adminMode?"Voltar ao tenant":"Administração global"}</Link>}<div className="sidebar-user"><span className="avatar">{me?.displayName?.slice(0,2).toUpperCase()}</span><div><strong>{me?.displayName}</strong><small>{adminMode?'Administrador global':context?.membershipType==='OWNER'?'Proprietário':'Membro'}</small></div><button onClick={logout} aria-label="Sair">↗</button></div></aside><main className="workspace"><button className="mobile-menu" onClick={()=>setMenu(!menu)}>☰ Menu</button>{adminMode&&<div className="elevated-banner">Ambiente administrativo global · Todas as ações são auditadas</div>}{!adminMode&&context?.platformAdmin&&<div className="elevated-banner">Acesso elevado ao tenant · Suas ações serão auditadas</div>}{adminMode?<AdminContent path={path}/>:tenantId&&context?<TenantContent path={path} tenantId={tenantId} context={context}/>:<div className="center-state"><p>Selecione ou cadastre uma empresa para continuar.</p></div>}</main>{me?.mustChangePassword&&<ForcedPasswordModal onChanged={()=>api<Me>("me").then(setMe)}/>}</div>
}

function PageHead({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <header className="page-head"><div><span className="kicker">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action&&<div className="actions">{action}</div>}</header>}
function TenantContent({path,tenantId,context}:{path:string;tenantId:string;context:Context}){
 if(path==='/app/formularios/novo')return <FormEditor tenantId={tenantId}/>;
 if(path.startsWith('/app/formularios/'))return <FormEditor tenantId={tenantId} id={path.split('/').pop()}/>;
 if(path==='/app/formularios')return <Forms tenantId={tenantId}/>;
 if(path.startsWith('/app/respostas'))return <Submissions tenantId={tenantId} detailId={path.split('/')[3]}/>;
 if(path==='/app/equipe')return <Team tenantId={tenantId}/>;
 if(path==='/app/acessos')return <AccessPanel tenantId={tenantId}/>;
 if(path==='/app/configuracoes')return <Settings tenantId={tenantId} context={context}/>;
 return <Overview tenantId={tenantId} context={context}/>;
}
function Overview({tenantId,context}:{tenantId:string;context:Context}){const [data,setData]=useState<any>();useEffect(()=>{api(`tenants/${tenantId}/dashboard`).then(setData)},[tenantId]);return <div className="page"><PageHead eyebrow="VISÃO GERAL" title={`Olá, ${context.tenant.name}`} description="Acompanhe a operação e continue de onde sua equipe parou."/><div className="metrics">{[['Formulários',data?.forms],['Respostas concluídas',data?.completedSubmissions],['Pessoas ativas',data?.activeMembers],['Rascunhos',data?.drafts]].map(x=><article className="metric" key={x[0]}><span>{x[0]}</span><strong>{x[1]??'—'}</strong></article>)}</div><div className="feature-panel"><div><span className="kicker">PRÓXIMO PASSO</span><h2>Estruture sua próxima inspeção</h2><p>Crie um formulário, publique uma versão e libere o acesso para a equipe de campo.</p><Link className="primary button" href="/app/formularios/novo">Criar formulário</Link></div><div className="workflow"><span>01 · Criar</span><span>02 · Publicar</span><span>03 · Distribuir</span><span>04 · Acompanhar</span></div></div></div>}
function Forms({tenantId}:{tenantId:string}){const [items,setItems]=useState<any[]>([]);const [error,setError]=useState('');const load=()=>api<any[]>(`tenants/${tenantId}/forms`).then(setItems).catch(e=>setError(e.message));useEffect(load,[tenantId]);async function status(id:string,archive:boolean){if(!confirm(archive?'Arquivar este formulário?':'Restaurar este formulário?'))return;await api(`tenants/${tenantId}/forms/${id}/${archive?'archive':'restore'}`,{method:'POST'});load()}return <div className="page"><PageHead eyebrow="OPERAÇÃO" title="Formulários" description="Crie, versione e distribua checklists para sua equipe." action={<Link className="primary button" href="/app/formularios/novo">Novo formulário</Link>}/>{error&&<div className="alert error">{error}</div>}<div className="table-card"><table><thead><tr><th>Nome</th><th>Status</th><th>Versão</th><th>Atualizado</th><th/></tr></thead><tbody>{items.map(f=><tr key={f.id}><td><strong>{f.name}</strong><small>{f.description||'Sem descrição'}</small></td><td><span className={`badge ${f.status.toLowerCase()}`}>{f.status}</span></td><td>{f.publishedVersion?`v${f.publishedVersion}`:'Ainda não publicado'}</td><td>{formatDate(f.updatedAt)}</td><td className="row-actions"><Link href={`/app/formularios/${f.id}`}>Editar</Link><button onClick={()=>status(f.id,f.status!=='ARCHIVED')}>{f.status==='ARCHIVED'?'Restaurar':'Arquivar'}</button></td></tr>)}</tbody></table>{items.length===0&&<div className="empty-state"><h3>Nenhum formulário ainda</h3><p>Comece criando o checklist da sua operação.</p></div>}</div></div>}
function Submissions({tenantId,detailId}:{tenantId:string;detailId?:string}){const [forms,setForms]=useState<any[]>([]);const [form,setForm]=useState('');const [items,setItems]=useState<any[]>([]);const [detail,setDetail]=useState<any>();useEffect(()=>{api<any[]>(`tenants/${tenantId}/forms`).then(v=>{setForms(v);setForm(v[0]?.id??'')})},[tenantId]);useEffect(()=>{if(form)api<any[]>(`tenants/${tenantId}/submissions?formId=${form}`).then(setItems)},[form,tenantId]);useEffect(()=>{if(detailId&&form)api(`tenants/${tenantId}/submissions/${detailId}?formId=${form}`).then(setDetail)},[detailId,form,tenantId]);if(detail)return <div className="page"><PageHead eyebrow="RESPOSTAS / DETALHE" title={`Resposta ${detail.id.slice(0,8)}`} description={`${detail.submittedByName} · ${formatDate(detail.submittedAt)}`}/><div className="detail-card">{Object.entries(detail.answers).map(([k,v])=><div key={k}><span>{k}</span><strong>{String(v)}</strong></div>)}</div></div>;return <div className="page"><PageHead eyebrow="CAMPO" title="Respostas" description="Consulte os registros enviados pela equipe."/><label className="filter">Formulário<select value={form} onChange={e=>setForm(e.target.value)}>{forms.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><div className="table-card"><table><thead><tr><th>Identificador</th><th>Status</th><th>Revisão</th><th>Atualizado</th><th/></tr></thead><tbody>{items.map(s=><tr key={s.id}><td>{s.id.slice(0,8)}</td><td><span className="badge">{s.status}</span></td><td>{s.revision}</td><td>{formatDate(s.updatedAt)}</td><td><Link href={`/app/respostas/${s.id}`}>Ver detalhes</Link></td></tr>)}</tbody></table>{items.length===0&&<div className="empty-state"><h3>Nenhuma resposta</h3><p>As inspeções concluídas aparecerão aqui.</p></div>}</div></div>}
function Team({tenantId}:{tenantId:string}){const [users,setUsers]=useState<any[]>([]);const [open,setOpen]=useState(false);const load=()=>api<any[]>(`tenants/${tenantId}/users`).then(setUsers);useEffect(load,[tenantId]);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api(`tenants/${tenantId}/users`,json('POST',d));setOpen(false);load()}async function toggle(u:any){await api(`tenants/${tenantId}/users/${u.membershipId}/status`,json('PATCH',{status:u.status==='ACTIVE'?'SUSPENDED':'ACTIVE'}));load()}return <div className="page"><PageHead eyebrow="PESSOAS" title="Equipe" description="Gerencie quem participa da operação." action={<button className="primary" onClick={()=>setOpen(true)}>Adicionar pessoa</button>}/><div className="cards-grid">{users.map(u=><article className="person-card" key={u.membershipId}><span className="avatar large">{u.displayName.slice(0,2).toUpperCase()}</span><div><h3>{u.displayName}</h3><p>{u.email}</p><span className="badge">{u.membershipType}</span></div>{!['OWNER','PLATFORM_ADMIN'].includes(u.membershipType)&&<button onClick={()=>toggle(u)}>{u.status==='ACTIVE'?'Suspender':'Ativar'}</button>}</article>)}</div>{open&&<div className="modal-backdrop"><form className="modal small" onSubmit={add}><h2>Adicionar pessoa</h2><label>Nome<input name="displayName" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Senha temporária<input name="temporaryPassword" type="password" minLength={10} required/></label><div className="actions"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">Adicionar</button></div></form></div>}</div>}
function Access({tenantId}:{tenantId:string}){const [roles,setRoles]=useState<any[]>([]);const [catalog,setCatalog]=useState<any[]>([]);const [users,setUsers]=useState<any[]>([]);const [access,setAccess]=useState<any>({assignments:[],grants:[]});const load=()=>Promise.all([api<any[]>(`tenants/${tenantId}/permissions/roles`),api<any[]>(`tenants/${tenantId}/permissions/catalog`),api<any[]>(`tenants/${tenantId}/users`),api<any>(`tenants/${tenantId}/permissions/access`)]).then(([r,c,u,a])=>{setRoles(r);setCatalog(c);setUsers(u);setAccess(a)});useEffect(load,[tenantId]);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api(`tenants/${tenantId}/permissions/roles`,json('POST',d));e.currentTarget.reset();load()}async function setPerm(role:any,code:string,on:boolean){const p=on?[...role.permissions,code]:role.permissions.filter((x:string)=>x!==code);await api(`tenants/${tenantId}/permissions/roles/${role.id}/permissions`,json('PUT',{permissions:p}));load()}async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api(`tenants/${tenantId}/permissions/roles/${d.roleId}/members/${d.membershipId}`,{method:'POST'});load()}return <div className="page"><PageHead eyebrow="SEGURANÇA" title="Papéis e acessos" description="Defina exatamente o que cada pessoa pode fazer."/><div className="split"><form className="panel" onSubmit={create}><h2>Novo papel</h2><label>Nome<input name="name" required/></label><label>Descrição<input name="description"/></label><button className="primary">Criar papel</button></form><form className="panel" onSubmit={assign}><h2>Atribuir papel</h2><label>Pessoa<select name="membershipId">{users.filter(u=>u.membershipType==='MEMBER').map(u=><option key={u.membershipId} value={u.membershipId}>{u.displayName}</option>)}</select></label><label>Papel<select name="roleId">{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="primary">Atribuir</button></form></div>{roles.map(r=><article className="role-card" key={r.id}><div><h3>{r.name}</h3><p>{r.description}</p></div><div className="permission-grid">{catalog.map(p=><label key={p.code}><input type="checkbox" checked={r.permissions.includes(p.code)} onChange={e=>setPerm(r,p.code,e.target.checked)}/><span><strong>{labels[p.code]??p.code}</strong><small>{p.description}</small></span></label>)}</div></article>)}</div>}
function Settings({tenantId,context}:{tenantId:string;context:Context}){async function tenant(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api(`tenants/${tenantId}`,json('PATCH',d));alert('Configurações salvas')}async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api('me/password',json('POST',d));e.currentTarget.reset();alert('Senha alterada')}return <div className="page"><PageHead eyebrow="PREFERÊNCIAS" title="Configurações" description="Atualize os dados da empresa e a segurança da sua conta."/><div className="settings-profile"><ProfileSettings/></div><div className="split"><form className="panel" onSubmit={tenant}><h2>Empresa</h2><label>Nome<input name="name" defaultValue={context.tenant.name}/></label><label>Fuso horário<input name="timezone" defaultValue={context.tenant.timezone}/></label><button className="primary">Salvar empresa</button></form><form className="panel" onSubmit={password}><h2>Alterar senha</h2><label>Senha atual<input name="currentPassword" type="password" required/></label><label>Nova senha<input name="newPassword" type="password" minLength={10} required/></label><button className="primary">Alterar senha</button></form></div></div>}
function AdminContent({path}:{path:string}){if(path==='/admin/tenants')return <AdminTenants/>;if(path==='/admin/usuarios')return <AdminUsers/>;return <AdminOverview/>}
function AdminOverview(){const [d,setD]=useState<any>();useEffect(()=>{api('admin/overview').then(setD)},[]);return <div className="page"><PageHead eyebrow="PLATAFORMA" title="Administração global" description="Saúde operacional de todos os clientes InspecTeam."/><div className="metrics">{[['Tenants',d?.tenants],['Tenants ativos',d?.activeTenants],['Usuários',d?.users],['Respostas',d?.completedSubmissions]].map(x=><article className="metric" key={x[0]}><span>{x[0]}</span><strong>{x[1]??'—'}</strong></article>)}</div></div>}
function AdminTenants(){const [data,setData]=useState<any>({items:[]});const [query,setQuery]=useState('');const load=()=>api<any>(`admin/tenants?query=${encodeURIComponent(query)}`).then(setData);useEffect(load,[]);async function status(id:string,status:string){await api(`admin/tenants/${id}/status`,json('PATCH',{status}));load()}async function enter(t:any){await api(`admin/tenants/${t.id}/enter`,{method:'POST'});localStorage.setItem('inspecteam_tenant',t.id);location.href='/app'}return <div className="page"><PageHead eyebrow="PLATAFORMA" title="Tenants" description="Consulte e opere as contas da plataforma."/><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nome ou identificador"/><button onClick={load}>Buscar</button></div><div className="table-card"><table><thead><tr><th>Tenant</th><th>Status</th><th>Membros</th><th>Formulários</th><th/></tr></thead><tbody>{data.items.map((t:any)=><tr key={t.id}><td><strong>{t.name}</strong><small>{t.slug}</small></td><td><span className="badge">{t.status}</span></td><td>{t.members}</td><td>{t.forms}</td><td className="row-actions"><button onClick={()=>enter(t)}>Acessar</button><select value={t.status} onChange={e=>status(t.id,e.target.value)}><option>ACTIVE</option><option>SUSPENDED</option><option>ARCHIVED</option></select></td></tr>)}</tbody></table></div></div>}
function AdminUsers(){const [data,setData]=useState<any>({items:[]});const [query,setQuery]=useState('');const load=()=>api<any>(`admin/users?query=${encodeURIComponent(query)}`).then(setData);useEffect(load,[]);async function update(id:string,path:string,body:any){await api(`admin/users/${id}/${path}`,json(path==='platform-admin'?'PUT':'PATCH',body));load()}return <div className="page"><PageHead eyebrow="PLATAFORMA" title="Usuários" description="Gerencie contas e administradores globais."/><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nome ou e-mail"/><button onClick={load}>Buscar</button></div><div className="table-card"><table><thead><tr><th>Usuário</th><th>Status</th><th>Admin global</th><th/></tr></thead><tbody>{data.items.map((u:any)=><tr key={u.id}><td><strong>{u.displayName}</strong><small>{u.email}</small></td><td>{u.status}</td><td><input type="checkbox" checked={u.platformAdmin} onChange={e=>update(u.id,'platform-admin',{enabled:e.target.checked})}/></td><td><button onClick={()=>update(u.id,'status',{status:u.status==='ACTIVE'?'SUSPENDED':'ACTIVE'})}>{u.status==='ACTIVE'?'Suspender':'Ativar'}</button></td></tr>)}</tbody></table></div></div>}
