import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";
const read=(file)=>readFile(new URL(`../${file}`,import.meta.url),"utf8");
test("aplicação expõe autenticação e áreas funcionais",async()=>{const workspace=await read("app/components/Workspace.tsx");const auth=await read("app/components/AuthForm.tsx");for(const label of ["Formulários","Respostas","Equipe","Acessos","Configurações","Administração global"])assert.match(workspace,new RegExp(label));assert.match(auth,/gateway\/auth/);});
test("sessão mantém tokens em cookies protegidos",async()=>{const session=await read("app/lib/server-session.ts");assert.match(session,/httpOnly: true/);assert.match(session,/sameSite: "lax"/);assert.doesNotMatch(await read("app/components/Workspace.tsx"),/localStorage\.setItem\([^,]*token/i);});
test("construtor suporta todos os tipos validados pela API",async()=>{const editor=await read("app/components/FormEditor.tsx");for(const type of ["text","textarea","number","date","time","select","multiselect","checkbox","photo","signature","heading","instructions"])assert.match(editor,new RegExp(`['\"]${type}['\"]`));});
test("senha temporária bloqueia a aplicação até a redefinição",async()=>{const modal=await read("app/components/ForcedPasswordModal.tsx");const workspace=await read("app/components/Workspace.tsx");assert.match(workspace,/mustChangePassword&&<ForcedPasswordModal/);assert.match(modal,/aria-modal="true"/);assert.match(modal,/me\/password/);assert.match(modal,/confirmPassword/);assert.doesNotMatch(modal,/onMouseDown|Fechar|Cancelar/);});
test("design system corporativo é centralizado e acessível",async()=>{const design=await read("app/components/DesignSystem.tsx");const styles=await read("app/styles/foundation.css");const workspace=await read("app/components/Workspace.tsx");assert.match(design,/@fluentui\/react-icons/);for(const token of ["--surface","--text-secondary","--focus","--accent-600"])assert.match(styles,new RegExp(token));assert.match(workspace,/Auditoria/);assert.doesNotMatch(workspace,/\bconfirm\(|\balert\(/);});

test("efeitos de carregamento não retornam Promise como cleanup",async()=>{for(const file of ["app/components/Workspace.tsx","app/components/AccessPanel.tsx"]){const source=await read(file);assert.doesNotMatch(source,/useEffect\s*\(\s*load\s*,/);assert.doesNotMatch(source,/useEffect\s*\(\s*async\b/);}const boundary=await read("app/error.tsx");assert.match(boundary,/reset/);assert.match(boundary,/Tentar novamente/);});

test("Vite filtra somente sourcemaps inválidos do Griffel",async()=>{const config=await read("vite.config.ts");assert.match(config,/createLogger/);assert.match(config,/node_modules\/@griffel/);assert.match(config,/outside its package/);assert.doesNotMatch(config,/logLevel\s*:\s*["']silent/);});
