import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { forwardRef, type ReactNode } from "react";
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View,type TextInputProps,type ViewStyle } from "react-native";
import { router,usePathname } from "expo-router";
import { radius,spacing,useTheme } from "@/core/design-system/theme";

export function Screen({children,scroll=true}:{children:ReactNode;scroll?:boolean}){const t=useTheme(),content=<View style={[s.content,{backgroundColor:t.canvas}]}>{children}</View>;return <SafeAreaView style={[s.safe,{backgroundColor:t.canvas}]}>{scroll?<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.scroll}>{content}</ScrollView>:content}</SafeAreaView>}
export function Header({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){const t=useTheme();return <View style={s.header}><View style={{flex:1}}>{eyebrow&&<Text style={[s.eyebrow,{color:t.accent700}]}>{eyebrow}</Text>}<Text accessibilityRole="header" style={[s.title,{color:t.text}]}>{title}</Text>{description&&<Text style={[s.description,{color:t.textSecondary}]}>{description}</Text>}</View>{action}</View>}
export function Card({children,style}:{children:ReactNode;style?:ViewStyle}){const t=useTheme();return <View style={[s.card,{backgroundColor:t.surface,borderColor:t.border},style]}>{children}</View>}
export function Button({label,onPress,icon,variant="primary",disabled,busy}:{label:string;onPress:()=>void;icon?:keyof typeof MaterialIcons.glyphMap;variant?:"primary"|"secondary"|"danger";disabled?:boolean;busy?:boolean}){const t=useTheme(),primary=variant==="primary";return <Pressable accessibilityRole="button" accessibilityState={{disabled:disabled||busy}} disabled={disabled||busy} onPress={onPress} style={({pressed})=>[s.button,{backgroundColor:primary?t.accent600:t.surface,borderColor:variant==="danger"?t.danger:primary?t.accent600:t.borderStrong,opacity:disabled||busy?0.55:pressed?0.82:1}]}>{busy?<ActivityIndicator color={primary?"#fff":t.text}/>:<>{icon&&<MaterialIcons name={icon} size={20} color={variant==="danger"?t.danger:primary?"#fff":t.text}/>}<Text style={[s.buttonText,{color:variant==="danger"?t.danger:primary?"#fff":t.text}]}>{label}</Text></>}</Pressable>}
export const Field=forwardRef<TextInput,TextInputProps&{label:string;error?:string}>(function Field({label,error,...props},ref){const t=useTheme();return <View style={s.field}><Text style={[s.fieldLabel,{color:t.text}]}>{label}</Text><TextInput ref={ref} placeholderTextColor={t.textSecondary} style={[s.input,{backgroundColor:t.surface,borderColor:error?t.danger:t.borderStrong,color:t.text}]} {...props}/>{error&&<Text accessibilityRole="alert" style={{color:t.danger}}>{error}</Text>}</View>})
export function StatusPill({label,tone="neutral"}:{label:string;tone?:"neutral"|"success"|"warning"|"danger"}){const t=useTheme(),colors=tone==="success"?[t.successSoft,t.success]:tone==="warning"?[t.warningSoft,t.warning]:tone==="danger"?[t.dangerSoft,t.danger]:[t.surfaceSubtle,t.textSecondary];return <View style={[s.pill,{backgroundColor:colors[0]}]}><Text style={[s.pillText,{color:colors[1]}]}>{label}</Text></View>}
export function Empty({icon,title,description}:{icon:keyof typeof MaterialIcons.glyphMap;title:string;description:string}){const t=useTheme();return <Card style={s.empty}><MaterialIcons name={icon} size={40} color={t.accent600}/><Text style={[s.emptyTitle,{color:t.text}]}>{title}</Text><Text style={[s.emptyDescription,{color:t.textSecondary}]}>{description}</Text></Card>}
export function BottomNav(){const path=usePathname(),t=useTheme(),items=[["description","Formulários","/(app)/formularios"],["sync","Pendências","/(app)/pendencias"],["settings","Ajustes","/(app)/configuracoes"]] as const;return <View style={[s.nav,{backgroundColor:t.surface,borderColor:t.border}]}>{items.map(([icon,label,href])=>{const active=path.includes(href.split("/").pop()!);return <Pressable key={href} accessibilityRole="tab" accessibilityState={{selected:active}} onPress={()=>router.replace(href)} style={s.navItem}><MaterialIcons name={icon} size={24} color={active?t.accent600:t.textSecondary}/><Text style={{color:active?t.accent700:t.textSecondary,fontWeight:active?"700":"500",fontSize:11}}>{label}</Text></Pressable>})}</View>}
const s=StyleSheet.create({safe:{flex:1},scroll:{flexGrow:1},content:{flex:1,padding:spacing.lg,gap:spacing.lg},header:{flexDirection:"row",gap:spacing.md,alignItems:"flex-start"},eyebrow:{fontSize:11,fontWeight:"800",letterSpacing:1.2,textTransform:"uppercase",marginBottom:4},title:{fontSize:28,lineHeight:34,fontWeight:"800",letterSpacing:-.7},description:{fontSize:14,lineHeight:21,marginTop:6},card:{borderWidth:1,borderRadius:radius.md,padding:spacing.lg},button:{minHeight:48,borderWidth:1,borderRadius:radius.sm,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},buttonText:{fontWeight:"700"},field:{gap:6},fieldLabel:{fontWeight:"700"},input:{minHeight:48,borderWidth:1,borderRadius:radius.sm,paddingHorizontal:12,fontSize:16},pill:{alignSelf:"flex-start",paddingHorizontal:9,paddingVertical:4,borderRadius:999},pillText:{fontSize:11,fontWeight:"800"},empty:{alignItems:"center",paddingVertical:32,gap:8},emptyTitle:{fontWeight:"800",fontSize:18},emptyDescription:{textAlign:"center",lineHeight:20},nav:{height:70,borderTopWidth:1,flexDirection:"row"},navItem:{flex:1,alignItems:"center",justifyContent:"center",gap:3}})
