package com.inspecteam.user.api;
import com.inspecteam.audit.application.AuditService;import com.inspecteam.permission.application.TenantAuthorizationService;import com.inspecteam.shared.exception.ApiException;import com.inspecteam.shared.security.CurrentUser;import jakarta.validation.Valid;import jakarta.validation.constraints.Pattern;import java.util.Map;import java.util.UUID;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.core.Authentication;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/tenants/{tenantId}/users") public class UserStatusController{
 private final JdbcClient jdbc;private final TenantAuthorizationService authorization;private final AuditService audit;
 public UserStatusController(JdbcClient jdbc,TenantAuthorizationService authorization,AuditService audit){this.jdbc=jdbc;this.authorization=authorization;this.audit=audit;}
 @PatchMapping("/{membershipId}/status") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional
 void status(@PathVariable UUID tenantId,@PathVariable UUID membershipId,@Valid @RequestBody StatusRequest request,Authentication auth){var actor=authorization.require(tenantId,CurrentUser.id(auth),CurrentUser.isPlatformAdmin(auth),"USER_UPDATE");int changed=jdbc.sql("UPDATE tenant_memberships SET status=:status,updated_at=NOW() WHERE tenant_id=:tenantId AND id=:id AND membership_type NOT IN ('OWNER','PLATFORM_ADMIN')").param("status",request.status()).param("tenantId",tenantId).param("id",membershipId).update();if(changed==0)throw new ApiException(HttpStatus.BAD_REQUEST,"Membership não encontrado ou protegido");audit.record(tenantId,CurrentUser.id(auth),actor==null?null:actor.id(),"USER_STATUS_CHANGED","MEMBERSHIP",membershipId,Map.of("status",request.status()));}
 record StatusRequest(@Pattern(regexp="ACTIVE|SUSPENDED")String status){}
}
